#RECRIA AS TABELAS DE INTERNAÇÃO ABAIXO PARA ALTERAR A FAIXA ETÁRIA, ISSO É FEITO POIS A FAIXA ETÁRIA 
#DA TABELA DE NÃO INTERNADOS ESTÁ DIFERENTE DA FAIXA ETÁRIA DA TABELA DE INTERNADOS

#TB_GT_SINISTRO_COMPETENCIA_CIRURGICA_ANALITICA
#TB_GT_SINISTRO_COMPETENCIA_CLINICA_ANALITICA
#TB_GT_SINISTRO_COMPETENCIA_DOMICILIAR_ANALITICA
#TB_GT_SINISTRO_COMPETENCIA_PARTO_ANALITICA
#TB_GT_SINISTRO_COMPETENCIA_PSIQUIATRICA_ANALITICA

#TABELAS NÃO GOVERNADAS QUE DEVEM SER ATUALIZADAS MANUALMENTE:
--self-service-saude.SANDBOX_SUCSI.TB_PLANO_AJUSTADO_COM_SOMPO #DEPARA DE PLANOS
--OBS IMPORTANTE: SE AS CLASSIFICAÇÕES DE PLANO CONSTANTES NO CAMPO NME_PLANO_AJUSTADO SE ALTERAREM, DEVE-SE ALTERAR 
--O CALCULO DA COLUNA PESO NA TB_EXPOSTOS_EXCEL
--------------------------------------------------------------------------------------------------------------------------------
#TB_GT_SINISTRO_COMPETENCIA_CIRURGICA_ANALITICA

#OBS: A TABELA self-service-saude.UDS_PRODUTO_DADOS.TB_COVID_SEGURADO_INTERNADO_copy não está sendo atualizada

CREATE OR REPLACE TABLE `self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_CIRURGICA_ANALITICA_LA_TESTE2`
OPTIONS (
    EXPIRATION_TIMESTAMP=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
)
AS

-- INTERNAÇÕES POR COVID
WITH CTE_COVID AS (
SELECT DISTINCT COD_IDENTIFICACAO, CAST(NUM_VPP AS STRING) AS NUM_VPP
  FROM `self-service-saude.UDS_PRODUTO_DADOS.TB_COVID_SEGURADO_INTERNADO_copy` 
 WHERE UPPER(RESULTADO_EXAME) = 'CONFIRMADO'  
)

-- PEGAR O VALOR PAGO POR INTERNAÇÃO
-- A SELEÇÃO FOI FEITA NA FAT_ITEM POIS OS PAGAMENTOS DOS SERVIÇO FEITOS NA REDE DEVEM SER CONSIDERADOS
-- PARA AS INTERNAÇÕES QUE SÃO "MISTAS", REDE E REEMBOLSO NA MESMA INTERNAÇÃO, NA FAT_INTERNAÇÃO OS VALORES JA ESTÃO SUMARIZADOS 

,CTE_SINISTRO AS (
SELECT  NUM_INTERNACAO
       ,COD_ANALITICO_BENEFICIARIO
       ,IF(COV.COD_IDENTIFICACAO IS NULL
           ,'N'
           ,'S'
          ) AS FLG_COVID
       ,SUM(VLR_PAGO_SERVICO) AS VLR_PAGO_INTERNACAO_TOTAL
       ,SUM(CASE WHEN S.FLG_HONORARIO_MEDICO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_HONORARIO_MEDICO
       ,SUM(CASE WHEN S.FLG_MATERIAL = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MATERIAL
       ,SUM(CASE WHEN S.FLG_MEDICAMENTO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MEDICAMENTO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_ITEM_SERVICO_SINISTRO` S
  LEFT JOIN CTE_COVID COV
    ON S.COD_CARTEIRINHA_BENEFICIARIO = COV.COD_IDENTIFICACAO
   AND S.NUM_VPP = COV.NUM_VPP
  WHERE S.DSC_TIPO_SINISTRO = 'REDE'
    AND S.FLG_INTERNACAO = 'S'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO >= '2018-01-01'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO < '2022-11-01'
  GROUP BY 1,2,3)

-- SINISTRO POR INTERNACAO ISOLANDO HM
,CTE_SUM_SIN AS (
SELECT *
      ,VLR_PAGO_INTERNACAO_TOTAL - IFNULL(VAL_CUSTO_HONORARIO_MEDICO,0) AS VAL_CUSTO_HOSPITALAR
  FROM CTE_SINISTRO)

--remover duplicidades do benef
,CTE_BENEFICIARIO AS
(
  SELECT DISTINCT
     DAT_NASCIMENTO
    ,COD_SEXO_BENEFICIARIO
    ,DSC_CARTEIRA
    ,NME_PLANO
    ,COD_ANALITICO_BENEFICIARIO
  FROM `self-service-saude-prd.REF_SAUDE_BENEFICIARIO.TB_CAD_BENEFICIARIO`
)

-- JUNTAR AS INFORMAÇÕES DE INTERNAÇÃO, BENEFICIARIO E PRESTADOR
,CTE_INTERNACAO AS (
SELECT SIN.NUM_INTERNACAO
      ,FORMAT_DATE("%Y",SIN.DAT_INTERNACAO) AS NUM_ANO_INTERNACAO
      ,FORMAT_DATE("%Y%m", SIN.DAT_INTERNACAO) AS NUM_ANO_MES_INTERNACAO
      ,FORMAT_DATE("%m", SIN.DAT_INTERNACAO) AS NUM_MES_INTERNACAO
      ,ITEM.COD_ANALITICO_BENEFICIARIO
      ,PREST.COD_PRESTADOR
      ,SIN.DSC_CLASSIFICACAO_PRESTADOR
      ,PREST.NME_PRESTADOR
      ,PREST.COD_GRUPO_ECONOMICO_PRESTADOR
      ,DATE_DIFF(SIN.DAT_INTERNACAO,BENEF.DAT_NASCIMENTO,YEAR) NUM_IDADE_BENEFICIARIO
      ,BENEF.COD_SEXO_BENEFICIARIO
      ,CASE WHEN BENEF.DSC_CARTEIRA = 'ADMINISTRADO'
            THEN 'ASO'
            WHEN BENEF.DSC_CARTEIRA LIKE 'PME%'
            THEN 'PME'
            ELSE BENEF.DSC_CARTEIRA 
        END AS DSC_CARTEIRA
      ,FAT.NME_PLANO
      ,PLAN.NME_PLANO_AJUSTADO
      ,SIN.NME_ESPECIALIDADE
      ,SIN.DSC_TIPO_INTERNACAO
      ,SIN.FLG_ORIGEM_PS
      ,SIN.DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,SIN.COD_PRINCIPAL_SERVICO
      ,ITEM.VLR_PAGO_INTERNACAO_TOTAL
      ,ITEM.VAL_CUSTO_HONORARIO_MEDICO
      ,ITEM.VAL_CUSTO_HOSPITALAR
      ,ITEM.VAL_CUSTO_MATERIAL
      ,ITEM.VAL_CUSTO_MEDICAMENTO
      ,ITEM.FLG_COVID
      ,SIN.FLG_DIARIA_UTI_GERAL
      
      ,SIN.FLG_DIARIA_PARTO_UTI_NEONATAL
      ,SIN.FLG_DIARIA_PARTO_UTI_ADULTO
      ,SIN.FLG_DIARIA_PARTO_UTI_GERAL
      
      ,SIN.FLG_INTERCORRENCIA
      ,SIN.FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,SIN.FLG_REINTERNACAO_MESMO_PRESTADOR
      ,SIN.QTD_PAGO_DIARIA_UTI_GERAL
      ,SIN.QTD_DIAS_INTERNADO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_INTERNACAO` SIN
 INNER JOIN CTE_SUM_SIN ITEM
    ON SIN.COD_ANALITICO_BENEFICIARIO = ITEM.COD_ANALITICO_BENEFICIARIO
   AND SIN.NUM_INTERNACAO = ITEM.NUM_INTERNACAO
  LEFT JOIN CTE_BENEFICIARIO BENEF
    ON SIN.COD_ANALITICO_BENEFICIARIO = BENEF.COD_ANALITICO_BENEFICIARIO
  LEFT JOIN `self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO` PREST
    ON SIN.COD_PRINCIPAL_PRESTADOR = PREST.COD_PRESTADOR

    LEFT JOIN `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_ITEM_SERVICO_SINISTRO` FAT
    ON SIN.COD_ANALITICO_BENEFICIARIO = FAT.COD_ANALITICO_BENEFICIARIO
    AND SIN.NUM_INTERNACAO = FAT.NUM_INTERNACAO

    LEFT JOIN self-service-saude.SANDBOX_GERAC.TB_PLANO_AJUSTADO_COM_SOMPO_LA PLAN
    ON FAT.NME_PLANO = PLAN.NME_PLANO #TRAZ O NME_PLANO_AJUSTADO DA TABELA DE DEPARA

  WHERE DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) >= '2018-01-01'
   AND DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) < '2022-11-01'
   AND SIN.DSC_TIPO_INTERNACAO = 'CIRURGICA'
   AND SIN.DSC_REGIME_INTERNACAO <> 'DOMICILIAR'
   
    
    )

-- SUMARIZAÇÃO E TRATAMENTOS

SELECT NUM_ANO_INTERNACAO
      ,NUM_ANO_MES_INTERNACAO
      ,NUM_INTERNACAO
      ,CASE WHEN NUM_MES_INTERNACAO BETWEEN '01' AND '03'
            THEN 'PRIMEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '04' AND '06'
            THEN 'SEGUNDO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '07' AND '09'
            THEN 'TERCEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '10' AND '12'
            THEN 'QUARTO TRIMESTRE'
            ELSE 'NAO INFORMADO'
         END AS DC_TRIMESTRE
      ,COD_ANALITICO_BENEFICIARIO
      ,COD_PRESTADOR
      ,DSC_CLASSIFICACAO_PRESTADOR
      ,NME_PRESTADOR
      ,COD_GRUPO_ECONOMICO_PRESTADOR
      ,CASE 
      WHEN NUM_IDADE_BENEFICIARIO <= 18                                   THEN 'ATE 18 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 19 AND NUM_IDADE_BENEFICIARIO <= 23  THEN 'DE 19 A 23 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 24 AND NUM_IDADE_BENEFICIARIO <= 28  THEN 'DE 24 A 28 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 29 AND NUM_IDADE_BENEFICIARIO <= 33  THEN 'DE 29 A 33 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 34 AND NUM_IDADE_BENEFICIARIO <= 38  THEN 'DE 34 A 38 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 39 AND NUM_IDADE_BENEFICIARIO <= 43  THEN 'DE 39 A 43 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 44 AND NUM_IDADE_BENEFICIARIO <= 48  THEN 'DE 44 A 48 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 49 AND NUM_IDADE_BENEFICIARIO <= 53  THEN 'DE 49 A 53 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 54 AND NUM_IDADE_BENEFICIARIO <= 58  THEN 'DE 54 A 58 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 59 AND NUM_IDADE_BENEFICIARIO <= 68  THEN 'DE 59 A 68 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 69 AND NUM_IDADE_BENEFICIARIO <= 78  THEN 'DE 69 A 78 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 79 AND NUM_IDADE_BENEFICIARIO <= 88  THEN 'DE 79 A 88 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 89 AND NUM_IDADE_BENEFICIARIO <= 98  THEN 'DE 89 A 98 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 99                                   THEN '99 ANOS OU MAIS'
      ELSE 'NÃO INFORMADO'
       END AS DSC_FAIXA_ETARIA
      ,COD_SEXO_BENEFICIARIO
      ,DSC_CARTEIRA
      ,NME_PLANO
      ,NME_PLANO_AJUSTADO
      ,NME_ESPECIALIDADE
      ,DSC_TIPO_INTERNACAO
      ,FLG_ORIGEM_PS
      ,FLG_COVID
      ,FLG_DIARIA_UTI_GERAL
      
      ,FLG_DIARIA_PARTO_UTI_NEONATAL
      ,FLG_DIARIA_PARTO_UTI_ADULTO
      ,FLG_DIARIA_PARTO_UTI_GERAL
      
      ,FLG_INTERCORRENCIA
      ,FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,FLG_REINTERNACAO_MESMO_PRESTADOR
      ,DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,COD_PRINCIPAL_SERVICO
      ,COUNT(NUM_INTERNACAO) QTD_INTERNACAO
      ,SUM(VLR_PAGO_INTERNACAO_TOTAL) AS VLR_PAGO_INTERNACAO_TOTAL
      ,SUM(VAL_CUSTO_HONORARIO_MEDICO) AS VAL_CUSTO_HONORARIO_MEDICO
      ,SUM(VAL_CUSTO_HOSPITALAR) AS VAL_CUSTO_HOSPITALAR
      ,SUM(VAL_CUSTO_MATERIAL) AS VAL_CUSTO_MATERIAL
      ,SUM(VAL_CUSTO_MEDICAMENTO) AS VAL_CUSTO_MEDICAMENTO
      ,SUM(QTD_PAGO_DIARIA_UTI_GERAL) AS QTD_PAGO_DIARIA_UTI_GERAL
      ,SUM(QTD_DIAS_INTERNADO) AS QTD_DIAS_INTERNADO
  FROM CTE_INTERNACAO      
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27

;


------------------------------------------------------------------------------------------------------------------
#TB_GT_SINISTRO_COMPETENCIA_CLINICA_ANALITICA



CREATE OR REPLACE TABLE `self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_CLINICA_ANALITICA_LA_TESTE`
OPTIONS (
    EXPIRATION_TIMESTAMP=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 10 DAY)
)

AS

-- INTERNAÇÕES POR COVID
WITH CTE_COVID AS (
SELECT DISTINCT COD_IDENTIFICACAO, CAST(NUM_VPP AS STRING) AS NUM_VPP
  FROM `self-service-saude.UDS_PRODUTO_DADOS.TB_COVID_SEGURADO_INTERNADO_copy` 
 WHERE UPPER(RESULTADO_EXAME) = 'CONFIRMADO'  
)

-- PEGAR O VALOR PAGO POR INTERNAÇÃO
-- A SELEÇÃO FOI FEITA NA FAT_ITEM POIS OS PAGAMENTOS DOS SERVIÇO FEITOS NA REDE DEVEM SER CONSIDERADOS
-- PARA AS INTERNAÇÕES QUE SÃO "MISTAS", REDE E REEMBOLSO NA MESMA INTERNAÇÃO, NA FAT_INTERNAÇÃO OS VALORES JA ESTÃO SUMARIZADOS 

,CTE_SINISTRO AS (
SELECT  NUM_INTERNACAO
       ,COD_ANALITICO_BENEFICIARIO
       ,IF(COV.COD_IDENTIFICACAO IS NULL
           ,'N'
           ,'S'
          ) AS FLG_COVID
       ,SUM(VLR_PAGO_SERVICO) AS VLR_PAGO_INTERNACAO_TOTAL
       ,SUM(CASE WHEN S.FLG_HONORARIO_MEDICO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_HONORARIO_MEDICO
       ,SUM(CASE WHEN S.FLG_MATERIAL = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MATERIAL
       ,SUM(CASE WHEN S.FLG_MEDICAMENTO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MEDICAMENTO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_ITEM_SERVICO_SINISTRO` S
  LEFT JOIN CTE_COVID COV
    ON S.COD_CARTEIRINHA_BENEFICIARIO = COV.COD_IDENTIFICACAO
   AND S.NUM_VPP = COV.NUM_VPP
  WHERE S.DSC_TIPO_SINISTRO = 'REDE'
    AND S.FLG_INTERNACAO = 'S'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO >= '2018-01-01'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO < '2022-11-01'
  GROUP BY 1,2,3)

-- SINISTRO POR INTERNACAO ISOLANDO HM
,CTE_SUM_SIN AS (
SELECT *
      ,VLR_PAGO_INTERNACAO_TOTAL - IFNULL(VAL_CUSTO_HONORARIO_MEDICO,0) AS VAL_CUSTO_HOSPITALAR
  FROM CTE_SINISTRO)

--remover duplicidades do benef
,CTE_BENEFICIARIO AS
(
  SELECT DISTINCT
     DAT_NASCIMENTO
    ,COD_SEXO_BENEFICIARIO
    ,DSC_CARTEIRA
    ,NME_PLANO
    ,COD_ANALITICO_BENEFICIARIO
  FROM `self-service-saude-prd.REF_SAUDE_BENEFICIARIO.TB_CAD_BENEFICIARIO`
)

-- JUNTAR AS INFORMAÇÕES DE INTERNAÇÃO, BENEFICIARIO E PRESTADOR
,CTE_INTERNACAO AS (
SELECT SIN.NUM_INTERNACAO
      ,FORMAT_DATE("%Y",SIN.DAT_INTERNACAO) AS NUM_ANO_INTERNACAO
      ,FORMAT_DATE("%Y%m", SIN.DAT_INTERNACAO) AS NUM_ANO_MES_INTERNACAO
      ,FORMAT_DATE("%m", SIN.DAT_INTERNACAO) AS NUM_MES_INTERNACAO
      ,ITEM.COD_ANALITICO_BENEFICIARIO
      ,PREST.COD_PRESTADOR
      ,SIN.DSC_CLASSIFICACAO_PRESTADOR
      ,PREST.NME_PRESTADOR
      ,PREST.COD_GRUPO_ECONOMICO_PRESTADOR
      ,DATE_DIFF(SIN.DAT_INTERNACAO,BENEF.DAT_NASCIMENTO,YEAR) NUM_IDADE_BENEFICIARIO
      ,BENEF.COD_SEXO_BENEFICIARIO
      ,CASE WHEN BENEF.DSC_CARTEIRA = 'ADMINISTRADO'
            THEN 'ASO'
            WHEN BENEF.DSC_CARTEIRA LIKE 'PME%'
            THEN 'PME'
            ELSE BENEF.DSC_CARTEIRA 
        END AS DSC_CARTEIRA
      ,BENEF.NME_PLANO 
      ,PLAN.NME_PLANO_AJUSTADO
      ,SIN.NME_ESPECIALIDADE
      ,SIN.DSC_TIPO_INTERNACAO
      ,SIN.FLG_ORIGEM_PS
      ,SIN.DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,SIN.COD_PRINCIPAL_SERVICO
      ,ITEM.VLR_PAGO_INTERNACAO_TOTAL
      ,ITEM.VAL_CUSTO_HONORARIO_MEDICO
      ,ITEM.VAL_CUSTO_HOSPITALAR
      ,ITEM.VAL_CUSTO_MATERIAL
      ,ITEM.VAL_CUSTO_MEDICAMENTO
      ,ITEM.FLG_COVID
      ,SIN.FLG_DIARIA_UTI_GERAL
      
      ,SIN.FLG_DIARIA_PARTO_UTI_NEONATAL
      ,SIN.FLG_DIARIA_PARTO_UTI_ADULTO
      ,SIN.FLG_DIARIA_PARTO_UTI_GERAL
      
      ,SIN.FLG_INTERCORRENCIA
      ,SIN.FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,SIN.FLG_REINTERNACAO_MESMO_PRESTADOR
      ,SIN.QTD_PAGO_DIARIA_UTI_GERAL
      ,SIN.QTD_DIAS_INTERNADO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_INTERNACAO` SIN
 INNER JOIN CTE_SUM_SIN ITEM
    ON SIN.COD_ANALITICO_BENEFICIARIO = ITEM.COD_ANALITICO_BENEFICIARIO
   AND SIN.NUM_INTERNACAO = ITEM.NUM_INTERNACAO
  LEFT JOIN CTE_BENEFICIARIO BENEF
    ON SIN.COD_ANALITICO_BENEFICIARIO = BENEF.COD_ANALITICO_BENEFICIARIO
  LEFT JOIN `self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO` PREST
    ON SIN.COD_PRINCIPAL_PRESTADOR = PREST.COD_PRESTADOR

    LEFT JOIN self-service-saude.SANDBOX_GERAC.TB_PLANO_AJUSTADO_COM_SOMPO_LA PLAN
    ON BENEF.NME_PLANO = PLAN.NME_PLANO #TRAZ O NME_PLANO_AJUSTADO DA TABELA DE DEPARA

  WHERE DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) >= '2018-01-01'
   AND DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) < '2022-11-01'
   AND SIN.DSC_TIPO_INTERNACAO = 'CLINICA'
   AND SIN.DSC_REGIME_INTERNACAO <> 'DOMICILIAR')

-- SUMARIZAÇÃO E TRATAMENTOS

SELECT NUM_ANO_INTERNACAO
      ,NUM_ANO_MES_INTERNACAO
      ,CASE WHEN NUM_MES_INTERNACAO BETWEEN '01' AND '03'
            THEN 'PRIMEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '04' AND '06'
            THEN 'SEGUNDO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '07' AND '09'
            THEN 'TERCEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '10' AND '12'
            THEN 'QUARTO TRIMESTRE'
            ELSE 'NAO INFORMADO'
         END AS DC_TRIMESTRE
      ,COD_ANALITICO_BENEFICIARIO
      ,COD_PRESTADOR
      ,DSC_CLASSIFICACAO_PRESTADOR
      ,NME_PRESTADOR
      ,COD_GRUPO_ECONOMICO_PRESTADOR
      ,CASE 
      WHEN NUM_IDADE_BENEFICIARIO <= 18                                   THEN 'ATE 18 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 19 AND NUM_IDADE_BENEFICIARIO <= 23  THEN 'DE 19 A 23 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 24 AND NUM_IDADE_BENEFICIARIO <= 28  THEN 'DE 24 A 28 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 29 AND NUM_IDADE_BENEFICIARIO <= 33  THEN 'DE 29 A 33 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 34 AND NUM_IDADE_BENEFICIARIO <= 38  THEN 'DE 34 A 38 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 39 AND NUM_IDADE_BENEFICIARIO <= 43  THEN 'DE 39 A 43 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 44 AND NUM_IDADE_BENEFICIARIO <= 48  THEN 'DE 44 A 48 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 49 AND NUM_IDADE_BENEFICIARIO <= 53  THEN 'DE 49 A 53 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 54 AND NUM_IDADE_BENEFICIARIO <= 58  THEN 'DE 54 A 58 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 59 AND NUM_IDADE_BENEFICIARIO <= 68  THEN 'DE 59 A 68 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 69 AND NUM_IDADE_BENEFICIARIO <= 78  THEN 'DE 69 A 78 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 79 AND NUM_IDADE_BENEFICIARIO <= 88  THEN 'DE 79 A 88 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 89 AND NUM_IDADE_BENEFICIARIO <= 98  THEN 'DE 89 A 98 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 99                                   THEN '99 ANOS OU MAIS'
      ELSE 'NÃO INFORMADO'
       END AS DSC_FAIXA_ETARIA
      ,COD_SEXO_BENEFICIARIO
      ,DSC_CARTEIRA
      ,NME_PLANO
      ,NME_PLANO_AJUSTADO
      ,NME_ESPECIALIDADE
      ,DSC_TIPO_INTERNACAO
      ,FLG_ORIGEM_PS
      ,FLG_COVID
      ,FLG_DIARIA_UTI_GERAL
     
      ,FLG_DIARIA_PARTO_UTI_NEONATAL
      ,FLG_DIARIA_PARTO_UTI_ADULTO
      ,FLG_DIARIA_PARTO_UTI_GERAL
      
      ,FLG_INTERCORRENCIA
      ,FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,FLG_REINTERNACAO_MESMO_PRESTADOR
      ,DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,COD_PRINCIPAL_SERVICO
      ,COUNT(NUM_INTERNACAO) QTD_INTERNACAO
      ,SUM(VLR_PAGO_INTERNACAO_TOTAL) AS VLR_PAGO_INTERNACAO_TOTAL
      ,SUM(VAL_CUSTO_HONORARIO_MEDICO) AS VAL_CUSTO_HONORARIO_MEDICO
      ,SUM(VAL_CUSTO_HOSPITALAR) AS VAL_CUSTO_HOSPITALAR
      ,SUM(VAL_CUSTO_MATERIAL) AS VAL_CUSTO_MATERIAL
      ,SUM(VAL_CUSTO_MEDICAMENTO) AS VAL_CUSTO_MEDICAMENTO
      ,SUM(QTD_PAGO_DIARIA_UTI_GERAL) AS QTD_PAGO_DIARIA_UTI_GERAL
      ,SUM(QTD_DIAS_INTERNADO) AS QTD_DIAS_INTERNADO
  FROM CTE_INTERNACAO      
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
 
;


------------------------------------------------------------------------------------------------------------------

#TB_GT_SINISTRO_COMPETENCIA_DOMICILIAR_ANALITICA



CREATE OR REPLACE TABLE `self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_DOMICILIAR_ANALITICA_LA_TESTE`
OPTIONS (
    EXPIRATION_TIMESTAMP=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 10 DAY)
)

AS

-- INTERNAÇÕES POR COVID
WITH CTE_COVID AS (
SELECT DISTINCT COD_IDENTIFICACAO, CAST(NUM_VPP AS STRING) AS NUM_VPP
  FROM `self-service-saude.UDS_PRODUTO_DADOS.TB_COVID_SEGURADO_INTERNADO_copy` 
 WHERE UPPER(RESULTADO_EXAME) = 'CONFIRMADO'  
)

-- PEGAR O VALOR PAGO POR INTERNAÇÃO
-- A SELEÇÃO FOI FEITA NA FAT_ITEM POIS OS PAGAMENTOS DOS SERVIÇO FEITOS NA REDE DEVEM SER CONSIDERADOS
-- PARA AS INTERNAÇÕES QUE SÃO "MISTAS", REDE E REEMBOLSO NA MESMA INTERNAÇÃO, NA FAT_INTERNAÇÃO OS VALORES JA ESTÃO SUMARIZADOS 

,CTE_SINISTRO AS (
SELECT  NUM_INTERNACAO
       ,COD_ANALITICO_BENEFICIARIO
       ,IF(COV.COD_IDENTIFICACAO IS NULL
           ,'N'
           ,'S'
          ) AS FLG_COVID
       ,SUM(VLR_PAGO_SERVICO) AS VLR_PAGO_INTERNACAO_TOTAL
       ,SUM(CASE WHEN S.FLG_HONORARIO_MEDICO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_HONORARIO_MEDICO
       ,SUM(CASE WHEN S.FLG_MATERIAL = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MATERIAL
       ,SUM(CASE WHEN S.FLG_MEDICAMENTO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MEDICAMENTO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_ITEM_SERVICO_SINISTRO` S
  LEFT JOIN CTE_COVID COV
    ON S.COD_CARTEIRINHA_BENEFICIARIO = COV.COD_IDENTIFICACAO
   AND S.NUM_VPP = COV.NUM_VPP
  WHERE S.DSC_TIPO_SINISTRO = 'REDE'
    AND S.FLG_INTERNACAO = 'S'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO >= '2018-01-01'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO < '2022-11-01'
  GROUP BY 1,2,3)

-- SINISTRO POR INTERNACAO ISOLANDO HM
,CTE_SUM_SIN AS (
SELECT *
      ,VLR_PAGO_INTERNACAO_TOTAL - IFNULL(VAL_CUSTO_HONORARIO_MEDICO,0) AS VAL_CUSTO_HOSPITALAR
  FROM CTE_SINISTRO)

--remover duplicidades do benef
,CTE_BENEFICIARIO AS
(
  SELECT DISTINCT
     DAT_NASCIMENTO
    ,COD_SEXO_BENEFICIARIO
    ,DSC_CARTEIRA
    ,NME_PLANO
    ,COD_ANALITICO_BENEFICIARIO
  FROM `self-service-saude-prd.REF_SAUDE_BENEFICIARIO.TB_CAD_BENEFICIARIO`
)

-- JUNTAR AS INFORMAÇÕES DE INTERNAÇÃO, BENEFICIARIO E PRESTADOR
,CTE_INTERNACAO AS (
SELECT SIN.NUM_INTERNACAO
      ,FORMAT_DATE("%Y",SIN.DAT_INTERNACAO) AS NUM_ANO_INTERNACAO
      ,FORMAT_DATE("%Y%m", SIN.DAT_INTERNACAO) AS NUM_ANO_MES_INTERNACAO
      ,FORMAT_DATE("%m", SIN.DAT_INTERNACAO) AS NUM_MES_INTERNACAO
      ,ITEM.COD_ANALITICO_BENEFICIARIO
      ,PREST.COD_PRESTADOR
      ,SIN.DSC_CLASSIFICACAO_PRESTADOR
      ,PREST.NME_PRESTADOR
      ,PREST.COD_GRUPO_ECONOMICO_PRESTADOR
      ,DATE_DIFF(SIN.DAT_INTERNACAO,BENEF.DAT_NASCIMENTO,YEAR) NUM_IDADE_BENEFICIARIO
      ,BENEF.COD_SEXO_BENEFICIARIO
      ,CASE WHEN BENEF.DSC_CARTEIRA = 'ADMINISTRADO'
            THEN 'ASO'
            WHEN BENEF.DSC_CARTEIRA LIKE 'PME%'
            THEN 'PME'
            ELSE BENEF.DSC_CARTEIRA 
        END AS DSC_CARTEIRA
      ,BENEF.NME_PLANO
      ,PLAN.NME_PLANO_AJUSTADO
      ,SIN.NME_ESPECIALIDADE
      ,SIN.DSC_TIPO_INTERNACAO
      ,SIN.FLG_ORIGEM_PS
      ,SIN.DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,SIN.COD_PRINCIPAL_SERVICO
      ,ITEM.VLR_PAGO_INTERNACAO_TOTAL
      ,ITEM.VAL_CUSTO_HONORARIO_MEDICO
      ,ITEM.VAL_CUSTO_HOSPITALAR
      ,ITEM.VAL_CUSTO_MATERIAL
      ,ITEM.VAL_CUSTO_MEDICAMENTO
      ,ITEM.FLG_COVID
      ,SIN.FLG_DIARIA_UTI_GERAL
      
      ,SIN.FLG_DIARIA_PARTO_UTI_NEONATAL
      ,SIN.FLG_DIARIA_PARTO_UTI_ADULTO
      ,SIN.FLG_DIARIA_PARTO_UTI_GERAL
      
      ,SIN.FLG_INTERCORRENCIA
      ,SIN.FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,SIN.FLG_REINTERNACAO_MESMO_PRESTADOR
      ,SIN.QTD_PAGO_DIARIA_UTI_GERAL
      ,SIN.QTD_DIAS_INTERNADO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_INTERNACAO` SIN
 INNER JOIN CTE_SUM_SIN ITEM
    ON SIN.COD_ANALITICO_BENEFICIARIO = ITEM.COD_ANALITICO_BENEFICIARIO
   AND SIN.NUM_INTERNACAO = ITEM.NUM_INTERNACAO
  LEFT JOIN CTE_BENEFICIARIO BENEF
    ON SIN.COD_ANALITICO_BENEFICIARIO = BENEF.COD_ANALITICO_BENEFICIARIO
  LEFT JOIN `self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO` PREST
    ON SIN.COD_PRINCIPAL_PRESTADOR = PREST.COD_PRESTADOR

       LEFT JOIN self-service-saude.SANDBOX_GERAC.TB_PLANO_AJUSTADO_COM_SOMPO_LA PLAN
    ON BENEF.NME_PLANO = PLAN.NME_PLANO #TRAZ O NME_PLANO_AJUSTADO DA TABELA DE DEPARA
    
 WHERE DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) >= '2018-01-01'
   AND DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) < '2022-11-01'
   AND SIN.DSC_REGIME_INTERNACAO = 'DOMICILIAR')

-- SUMARIZAÇÃO E TRATAMENTOS

SELECT NUM_ANO_INTERNACAO
      ,NUM_ANO_MES_INTERNACAO
      ,CASE WHEN NUM_MES_INTERNACAO BETWEEN '01' AND '03'
            THEN 'PRIMEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '04' AND '06'
            THEN 'SEGUNDO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '07' AND '09'
            THEN 'TERCEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '10' AND '12'
            THEN 'QUARTO TRIMESTRE'
            ELSE 'NAO INFORMADO'
         END AS DC_TRIMESTRE
      ,COD_ANALITICO_BENEFICIARIO
      ,COD_PRESTADOR
      ,DSC_CLASSIFICACAO_PRESTADOR
      ,NME_PRESTADOR
      ,COD_GRUPO_ECONOMICO_PRESTADOR
      ,CASE 
      WHEN NUM_IDADE_BENEFICIARIO <= 18                                   THEN 'ATE 18 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 19 AND NUM_IDADE_BENEFICIARIO <= 23  THEN 'DE 19 A 23 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 24 AND NUM_IDADE_BENEFICIARIO <= 28  THEN 'DE 24 A 28 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 29 AND NUM_IDADE_BENEFICIARIO <= 33  THEN 'DE 29 A 33 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 34 AND NUM_IDADE_BENEFICIARIO <= 38  THEN 'DE 34 A 38 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 39 AND NUM_IDADE_BENEFICIARIO <= 43  THEN 'DE 39 A 43 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 44 AND NUM_IDADE_BENEFICIARIO <= 48  THEN 'DE 44 A 48 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 49 AND NUM_IDADE_BENEFICIARIO <= 53  THEN 'DE 49 A 53 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 54 AND NUM_IDADE_BENEFICIARIO <= 58  THEN 'DE 54 A 58 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 59 AND NUM_IDADE_BENEFICIARIO <= 68  THEN 'DE 59 A 68 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 69 AND NUM_IDADE_BENEFICIARIO <= 78  THEN 'DE 69 A 78 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 79 AND NUM_IDADE_BENEFICIARIO <= 88  THEN 'DE 79 A 88 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 89 AND NUM_IDADE_BENEFICIARIO <= 98  THEN 'DE 89 A 98 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 99                                   THEN '99 ANOS OU MAIS'
      ELSE 'NÃO INFORMADO'
       END AS DSC_FAIXA_ETARIA
      ,COD_SEXO_BENEFICIARIO
      ,DSC_CARTEIRA
      ,NME_PLANO
      ,NME_PLANO_AJUSTADO
      ,NME_ESPECIALIDADE
      ,DSC_TIPO_INTERNACAO
      ,FLG_ORIGEM_PS
      ,FLG_COVID
      ,FLG_DIARIA_UTI_GERAL
    
      ,FLG_DIARIA_PARTO_UTI_NEONATAL
      ,FLG_DIARIA_PARTO_UTI_ADULTO
      ,FLG_DIARIA_PARTO_UTI_GERAL
      
      ,FLG_INTERCORRENCIA
      ,FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,FLG_REINTERNACAO_MESMO_PRESTADOR
      ,DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,COD_PRINCIPAL_SERVICO
      ,COUNT(NUM_INTERNACAO) QTD_INTERNACAO
      ,SUM(VLR_PAGO_INTERNACAO_TOTAL) AS VLR_PAGO_INTERNACAO_TOTAL
      ,SUM(VAL_CUSTO_HONORARIO_MEDICO) AS VAL_CUSTO_HONORARIO_MEDICO
      ,SUM(VAL_CUSTO_HOSPITALAR) AS VAL_CUSTO_HOSPITALAR
      ,SUM(VAL_CUSTO_MATERIAL) AS VAL_CUSTO_MATERIAL
      ,SUM(VAL_CUSTO_MEDICAMENTO) AS VAL_CUSTO_MEDICAMENTO
      ,SUM(QTD_PAGO_DIARIA_UTI_GERAL) AS QTD_PAGO_DIARIA_UTI_GERAL
      ,SUM(QTD_DIAS_INTERNADO) AS QTD_DIAS_INTERNADO
  FROM CTE_INTERNACAO      
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26

;


------------------------------------------------------------------------------------------------------------------



#TB_GT_SINISTRO_COMPETENCIA_PARTO_ANALITICA

CREATE OR REPLACE TABLE `self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_PARTO_ANALITICA_LA_TESTE`
OPTIONS (
    EXPIRATION_TIMESTAMP=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 10 DAY)
)

AS

-- INTERNAÇÕES POR COVID
WITH CTE_COVID AS (
SELECT DISTINCT COD_IDENTIFICACAO, CAST(NUM_VPP AS STRING) AS NUM_VPP
  FROM `self-service-saude.UDS_PRODUTO_DADOS.TB_COVID_SEGURADO_INTERNADO_copy` 
 WHERE UPPER(RESULTADO_EXAME) = 'CONFIRMADO'  
)

-- PEGAR O VALOR PAGO POR INTERNAÇÃO
-- A SELEÇÃO FOI FEITA NA FAT_ITEM POIS OS PAGAMENTOS DOS SERVIÇO FEITOS NA REDE DEVEM SER CONSIDERADOS
-- PARA AS INTERNAÇÕES QUE SÃO "MISTAS", REDE E REEMBOLSO NA MESMA INTERNAÇÃO, NA FAT_INTERNAÇÃO OS VALORES JA ESTÃO SUMARIZADOS 

,CTE_SINISTRO AS (
SELECT  NUM_INTERNACAO
       ,COD_ANALITICO_BENEFICIARIO
       ,IF(COV.COD_IDENTIFICACAO IS NULL
           ,'N'
           ,'S'
          ) AS FLG_COVID
       ,SUM(VLR_PAGO_SERVICO) AS VLR_PAGO_INTERNACAO_TOTAL
       ,SUM(CASE WHEN S.FLG_HONORARIO_MEDICO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_HONORARIO_MEDICO
       ,SUM(CASE WHEN S.FLG_MATERIAL = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MATERIAL
       ,SUM(CASE WHEN S.FLG_MEDICAMENTO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MEDICAMENTO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_ITEM_SERVICO_SINISTRO` S
  LEFT JOIN CTE_COVID COV
    ON S.COD_CARTEIRINHA_BENEFICIARIO = COV.COD_IDENTIFICACAO
   AND S.NUM_VPP = COV.NUM_VPP
  WHERE S.DSC_TIPO_SINISTRO = 'REDE'
    AND S.FLG_INTERNACAO = 'S'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO >= '2018-01-01'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO < '2022-11-01'
  GROUP BY 1,2,3)

-- SINISTRO POR INTERNACAO ISOLANDO HM
,CTE_SUM_SIN AS (
SELECT *
      ,VLR_PAGO_INTERNACAO_TOTAL - IFNULL(VAL_CUSTO_HONORARIO_MEDICO,0) AS VAL_CUSTO_HOSPITALAR
  FROM CTE_SINISTRO)

--remover duplicidades do benef
,CTE_BENEFICIARIO AS
(
  SELECT DISTINCT
     DAT_NASCIMENTO
    ,COD_SEXO_BENEFICIARIO
    ,DSC_CARTEIRA
    ,NME_PLANO
    ,COD_ANALITICO_BENEFICIARIO
  FROM `self-service-saude-prd.REF_SAUDE_BENEFICIARIO.TB_CAD_BENEFICIARIO`
)

-- JUNTAR AS INFORMAÇÕES DE INTERNAÇÃO, BENEFICIARIO E PRESTADOR
,CTE_INTERNACAO AS (
SELECT SIN.NUM_INTERNACAO
      ,FORMAT_DATE("%Y",SIN.DAT_INTERNACAO) AS NUM_ANO_INTERNACAO
      ,FORMAT_DATE("%Y%m", SIN.DAT_INTERNACAO) AS NUM_ANO_MES_INTERNACAO
      ,FORMAT_DATE("%m", SIN.DAT_INTERNACAO) AS NUM_MES_INTERNACAO
      ,ITEM.COD_ANALITICO_BENEFICIARIO
      ,PREST.COD_PRESTADOR
      ,SIN.DSC_CLASSIFICACAO_PRESTADOR
      ,PREST.NME_PRESTADOR
      ,PREST.COD_GRUPO_ECONOMICO_PRESTADOR
      ,DATE_DIFF(SIN.DAT_INTERNACAO,BENEF.DAT_NASCIMENTO,YEAR) NUM_IDADE_BENEFICIARIO
      ,BENEF.COD_SEXO_BENEFICIARIO
      ,CASE WHEN BENEF.DSC_CARTEIRA = 'ADMINISTRADO'
            THEN 'ASO'
            WHEN BENEF.DSC_CARTEIRA LIKE 'PME%'
            THEN 'PME'
            ELSE BENEF.DSC_CARTEIRA 
        END AS DSC_CARTEIRA
      ,BENEF.NME_PLANO
      ,PLAN.NME_PLANO_AJUSTADO
      ,SIN.NME_ESPECIALIDADE
      ,SIN.DSC_TIPO_INTERNACAO
      ,SIN.FLG_ORIGEM_PS
      ,SIN.DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,SIN.COD_PRINCIPAL_SERVICO
      ,ITEM.VLR_PAGO_INTERNACAO_TOTAL
      ,ITEM.VAL_CUSTO_HONORARIO_MEDICO
      ,ITEM.VAL_CUSTO_HOSPITALAR
      ,ITEM.VAL_CUSTO_MATERIAL
      ,ITEM.VAL_CUSTO_MEDICAMENTO
      ,ITEM.FLG_COVID
      ,SIN.FLG_DIARIA_UTI_GERAL

      ,SIN.FLG_DIARIA_PARTO_UTI_NEONATAL
      ,SIN.FLG_DIARIA_PARTO_UTI_ADULTO
      ,SIN.FLG_DIARIA_PARTO_UTI_GERAL

      ,SIN.FLG_INTERCORRENCIA
      ,SIN.FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,SIN.FLG_REINTERNACAO_MESMO_PRESTADOR
      ,SIN.QTD_PAGO_DIARIA_UTI_GERAL
      ,SIN.QTD_DIAS_INTERNADO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_INTERNACAO` SIN
 INNER JOIN CTE_SUM_SIN ITEM
    ON SIN.COD_ANALITICO_BENEFICIARIO = ITEM.COD_ANALITICO_BENEFICIARIO
   AND SIN.NUM_INTERNACAO = ITEM.NUM_INTERNACAO
  LEFT JOIN CTE_BENEFICIARIO BENEF
    ON SIN.COD_ANALITICO_BENEFICIARIO = BENEF.COD_ANALITICO_BENEFICIARIO
  LEFT JOIN `self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO` PREST
    ON SIN.COD_PRINCIPAL_PRESTADOR = PREST.COD_PRESTADOR

           LEFT JOIN self-service-saude.SANDBOX_GERAC.TB_PLANO_AJUSTADO_COM_SOMPO_LA PLAN
    ON BENEF.NME_PLANO = PLAN.NME_PLANO #TRAZ O NME_PLANO_AJUSTADO DA TABELA DE DEPARA

 WHERE DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) >= '2018-01-01'
   AND DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) < '2022-11-01'
   AND SIN.DSC_TIPO_INTERNACAO = 'PARTO'
   AND SIN.DSC_REGIME_INTERNACAO <> 'DOMICILIAR')

-- SUMARIZAÇÃO E TRATAMENTOS

SELECT NUM_ANO_INTERNACAO
      ,NUM_ANO_MES_INTERNACAO
      ,CASE WHEN NUM_MES_INTERNACAO BETWEEN '01' AND '03'
            THEN 'PRIMEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '04' AND '06'
            THEN 'SEGUNDO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '07' AND '09'
            THEN 'TERCEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '10' AND '12'
            THEN 'QUARTO TRIMESTRE'
            ELSE 'NAO INFORMADO'
         END AS DC_TRIMESTRE
      ,COD_ANALITICO_BENEFICIARIO
      ,COD_PRESTADOR
      ,DSC_CLASSIFICACAO_PRESTADOR
      ,NME_PRESTADOR
      ,COD_GRUPO_ECONOMICO_PRESTADOR
       ,CASE 
      WHEN NUM_IDADE_BENEFICIARIO <= 18                                   THEN 'ATE 18 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 19 AND NUM_IDADE_BENEFICIARIO <= 23  THEN 'DE 19 A 23 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 24 AND NUM_IDADE_BENEFICIARIO <= 28  THEN 'DE 24 A 28 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 29 AND NUM_IDADE_BENEFICIARIO <= 33  THEN 'DE 29 A 33 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 34 AND NUM_IDADE_BENEFICIARIO <= 38  THEN 'DE 34 A 38 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 39 AND NUM_IDADE_BENEFICIARIO <= 43  THEN 'DE 39 A 43 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 44 AND NUM_IDADE_BENEFICIARIO <= 48  THEN 'DE 44 A 48 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 49 AND NUM_IDADE_BENEFICIARIO <= 53  THEN 'DE 49 A 53 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 54 AND NUM_IDADE_BENEFICIARIO <= 58  THEN 'DE 54 A 58 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 59 AND NUM_IDADE_BENEFICIARIO <= 68  THEN 'DE 59 A 68 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 69 AND NUM_IDADE_BENEFICIARIO <= 78  THEN 'DE 69 A 78 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 79 AND NUM_IDADE_BENEFICIARIO <= 88  THEN 'DE 79 A 88 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 89 AND NUM_IDADE_BENEFICIARIO <= 98  THEN 'DE 89 A 98 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 99                                   THEN '99 ANOS OU MAIS'
      ELSE 'NÃO INFORMADO'
       END AS DSC_FAIXA_ETARIA
      ,COD_SEXO_BENEFICIARIO
      ,DSC_CARTEIRA
      ,NME_PLANO
      ,NME_PLANO_AJUSTADO
      ,NME_ESPECIALIDADE
      ,DSC_TIPO_INTERNACAO
      ,FLG_ORIGEM_PS
      ,FLG_COVID
      ,FLG_DIARIA_UTI_GERAL
    
      ,FLG_DIARIA_PARTO_UTI_NEONATAL
      ,FLG_DIARIA_PARTO_UTI_ADULTO
      ,FLG_DIARIA_PARTO_UTI_GERAL
      
      ,FLG_INTERCORRENCIA
      ,FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,FLG_REINTERNACAO_MESMO_PRESTADOR
      ,DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,COD_PRINCIPAL_SERVICO
      ,COUNT(NUM_INTERNACAO) QTD_INTERNACAO
      ,SUM(VLR_PAGO_INTERNACAO_TOTAL) AS VLR_PAGO_INTERNACAO_TOTAL
      ,SUM(VAL_CUSTO_HONORARIO_MEDICO) AS VAL_CUSTO_HONORARIO_MEDICO
      ,SUM(VAL_CUSTO_HOSPITALAR) AS VAL_CUSTO_HOSPITALAR
      ,SUM(VAL_CUSTO_MATERIAL) AS VAL_CUSTO_MATERIAL
      ,SUM(VAL_CUSTO_MEDICAMENTO) AS VAL_CUSTO_MEDICAMENTO
      ,SUM(QTD_PAGO_DIARIA_UTI_GERAL) AS QTD_PAGO_DIARIA_UTI_GERAL
      ,SUM(QTD_DIAS_INTERNADO) AS QTD_DIAS_INTERNADO
  FROM CTE_INTERNACAO      
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
 
;


------------------------------------------------------------------------------------------------------------------



#TB_GT_SINISTRO_COMPETENCIA_PSIQUIATRICA_ANALITICA

CREATE OR REPLACE TABLE `self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_PSIQUIATRICA_ANALITICA_LA_TESTE`
OPTIONS (
    EXPIRATION_TIMESTAMP=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 10 DAY)
)

AS

-- INTERNAÇÕES POR COVID
WITH CTE_COVID AS (
SELECT DISTINCT COD_IDENTIFICACAO, CAST(NUM_VPP AS STRING) AS NUM_VPP
  FROM `self-service-saude.UDS_PRODUTO_DADOS.TB_COVID_SEGURADO_INTERNADO_copy` 
 WHERE UPPER(RESULTADO_EXAME) = 'CONFIRMADO'  
)

-- PEGAR O VALOR PAGO POR INTERNAÇÃO
-- A SELEÇÃO FOI FEITA NA FAT_ITEM POIS OS PAGAMENTOS DOS SERVIÇO FEITOS NA REDE DEVEM SER CONSIDERADOS
-- PARA AS INTERNAÇÕES QUE SÃO "MISTAS", REDE E REEMBOLSO NA MESMA INTERNAÇÃO, NA FAT_INTERNAÇÃO OS VALORES JA ESTÃO SUMARIZADOS 

,CTE_SINISTRO AS (
SELECT  NUM_INTERNACAO
       ,COD_ANALITICO_BENEFICIARIO
       ,IF(COV.COD_IDENTIFICACAO IS NULL
           ,'N'
           ,'S'
          ) AS FLG_COVID
       ,SUM(VLR_PAGO_SERVICO) AS VLR_PAGO_INTERNACAO_TOTAL
       ,SUM(CASE WHEN S.FLG_HONORARIO_MEDICO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_HONORARIO_MEDICO
       ,SUM(CASE WHEN S.FLG_MATERIAL = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MATERIAL
       ,SUM(CASE WHEN S.FLG_MEDICAMENTO = 'S'
                 THEN S.VLR_PAGO_SERVICO
                 ELSE 0
            END) AS VAL_CUSTO_MEDICAMENTO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_ITEM_SERVICO_SINISTRO` S
  LEFT JOIN CTE_COVID COV
    ON S.COD_CARTEIRINHA_BENEFICIARIO = COV.COD_IDENTIFICACAO
   AND S.NUM_VPP = COV.NUM_VPP
  WHERE S.DSC_TIPO_SINISTRO = 'REDE'
    AND S.FLG_INTERNACAO = 'S'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO >= '2018-01-01'
    --AND S.DAT_ATENDIMENTO_EFETIVO_SINISTRO < '2022-11-01'
  GROUP BY 1,2,3)

-- SINISTRO POR INTERNACAO ISOLANDO HM
,CTE_SUM_SIN AS (
SELECT *
      ,VLR_PAGO_INTERNACAO_TOTAL - IFNULL(VAL_CUSTO_HONORARIO_MEDICO,0) AS VAL_CUSTO_HOSPITALAR
  FROM CTE_SINISTRO)

--remover duplicidades do benef
,CTE_BENEFICIARIO AS
(
  SELECT DISTINCT
     DAT_NASCIMENTO
    ,COD_SEXO_BENEFICIARIO
    ,DSC_CARTEIRA
    ,NME_PLANO
    ,COD_ANALITICO_BENEFICIARIO
  FROM `self-service-saude-prd.REF_SAUDE_BENEFICIARIO.TB_CAD_BENEFICIARIO`
)

-- JUNTAR AS INFORMAÇÕES DE INTERNAÇÃO, BENEFICIARIO E PRESTADOR
,CTE_INTERNACAO AS (
SELECT SIN.NUM_INTERNACAO
      ,FORMAT_DATE("%Y",SIN.DAT_INTERNACAO) AS NUM_ANO_INTERNACAO
      ,FORMAT_DATE("%Y%m", SIN.DAT_INTERNACAO) AS NUM_ANO_MES_INTERNACAO
      ,FORMAT_DATE("%m", SIN.DAT_INTERNACAO) AS NUM_MES_INTERNACAO
      ,ITEM.COD_ANALITICO_BENEFICIARIO
      ,PREST.COD_PRESTADOR
      ,SIN.DSC_CLASSIFICACAO_PRESTADOR
      ,PREST.NME_PRESTADOR
      ,PREST.COD_GRUPO_ECONOMICO_PRESTADOR
      ,DATE_DIFF(SIN.DAT_INTERNACAO,BENEF.DAT_NASCIMENTO,YEAR) NUM_IDADE_BENEFICIARIO
      ,BENEF.COD_SEXO_BENEFICIARIO
      ,CASE WHEN BENEF.DSC_CARTEIRA = 'ADMINISTRADO'
            THEN 'ASO'
            WHEN BENEF.DSC_CARTEIRA LIKE 'PME%'
            THEN 'PME'
            ELSE BENEF.DSC_CARTEIRA 
        END AS DSC_CARTEIRA
      ,BENEF.NME_PLANO
      ,PLAN.NME_PLANO_AJUSTADO
      ,SIN.NME_ESPECIALIDADE
      ,SIN.DSC_TIPO_INTERNACAO
      ,SIN.FLG_ORIGEM_PS
      ,SIN.DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,SIN.COD_PRINCIPAL_SERVICO
      ,ITEM.VLR_PAGO_INTERNACAO_TOTAL
      ,ITEM.VAL_CUSTO_HONORARIO_MEDICO
      ,ITEM.VAL_CUSTO_HOSPITALAR
      ,ITEM.VAL_CUSTO_MATERIAL
      ,ITEM.VAL_CUSTO_MEDICAMENTO
      ,ITEM.FLG_COVID
      ,SIN.FLG_DIARIA_UTI_GERAL
      
      ,SIN.FLG_DIARIA_PARTO_UTI_NEONATAL
      ,SIN.FLG_DIARIA_PARTO_UTI_ADULTO
      ,SIN.FLG_DIARIA_PARTO_UTI_GERAL
      
      ,SIN.FLG_INTERCORRENCIA
      ,SIN.FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,SIN.FLG_REINTERNACAO_MESMO_PRESTADOR
      ,SIN.QTD_PAGO_DIARIA_UTI_GERAL
      ,SIN.QTD_DIAS_INTERNADO
  FROM `self-service-saude-prd.REF_SAUDE_ESTRATEGIA_SINISTRO.TB_FAT_INTERNACAO` SIN
 INNER JOIN CTE_SUM_SIN ITEM
    ON SIN.COD_ANALITICO_BENEFICIARIO = ITEM.COD_ANALITICO_BENEFICIARIO
   AND SIN.NUM_INTERNACAO = ITEM.NUM_INTERNACAO
  LEFT JOIN CTE_BENEFICIARIO BENEF
    ON SIN.COD_ANALITICO_BENEFICIARIO = BENEF.COD_ANALITICO_BENEFICIARIO
  LEFT JOIN `self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO` PREST
    ON SIN.COD_PRINCIPAL_PRESTADOR = PREST.COD_PRESTADOR

    LEFT JOIN self-service-saude.SANDBOX_GERAC.TB_PLANO_AJUSTADO_COM_SOMPO_LA PLAN
    ON BENEF.NME_PLANO = PLAN.NME_PLANO #TRAZ O NME_PLANO_AJUSTADO DA TABELA DE DEPARA

 WHERE DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) >= '2018-01-01'
   AND DATE_TRUNC(SIN.DAT_INTERNACAO, MONTH) < '2022-11-01'
   AND SIN.DSC_TIPO_INTERNACAO = 'PSIQUIATRICA'
   AND SIN.DSC_REGIME_INTERNACAO <> 'DOMICILIAR')

-- SUMARIZAÇÃO E TRATAMENTOS

SELECT NUM_ANO_INTERNACAO
      ,NUM_ANO_MES_INTERNACAO
      ,CASE WHEN NUM_MES_INTERNACAO BETWEEN '01' AND '03'
            THEN 'PRIMEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '04' AND '06'
            THEN 'SEGUNDO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '07' AND '09'
            THEN 'TERCEIRO TRIMESTRE'
            WHEN NUM_MES_INTERNACAO BETWEEN '10' AND '12'
            THEN 'QUARTO TRIMESTRE'
            ELSE 'NAO INFORMADO'
         END AS DC_TRIMESTRE
      ,COD_ANALITICO_BENEFICIARIO
      ,COD_PRESTADOR
      ,DSC_CLASSIFICACAO_PRESTADOR
      ,NME_PRESTADOR
      ,COD_GRUPO_ECONOMICO_PRESTADOR
        ,CASE 
      WHEN NUM_IDADE_BENEFICIARIO <= 18                                   THEN 'ATE 18 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 19 AND NUM_IDADE_BENEFICIARIO <= 23  THEN 'DE 19 A 23 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 24 AND NUM_IDADE_BENEFICIARIO <= 28  THEN 'DE 24 A 28 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 29 AND NUM_IDADE_BENEFICIARIO <= 33  THEN 'DE 29 A 33 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 34 AND NUM_IDADE_BENEFICIARIO <= 38  THEN 'DE 34 A 38 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 39 AND NUM_IDADE_BENEFICIARIO <= 43  THEN 'DE 39 A 43 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 44 AND NUM_IDADE_BENEFICIARIO <= 48  THEN 'DE 44 A 48 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 49 AND NUM_IDADE_BENEFICIARIO <= 53  THEN 'DE 49 A 53 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 54 AND NUM_IDADE_BENEFICIARIO <= 58  THEN 'DE 54 A 58 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 59 AND NUM_IDADE_BENEFICIARIO <= 68  THEN 'DE 59 A 68 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 69 AND NUM_IDADE_BENEFICIARIO <= 78  THEN 'DE 69 A 78 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 79 AND NUM_IDADE_BENEFICIARIO <= 88  THEN 'DE 79 A 88 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 89 AND NUM_IDADE_BENEFICIARIO <= 98  THEN 'DE 89 A 98 ANOS'
      WHEN NUM_IDADE_BENEFICIARIO >= 99                                   THEN '99 ANOS OU MAIS'
      ELSE 'NÃO INFORMADO'
       END AS DSC_FAIXA_ETARIA
      ,COD_SEXO_BENEFICIARIO
      ,DSC_CARTEIRA
      ,NME_PLANO
      ,NME_PLANO_AJUSTADO
      ,NME_ESPECIALIDADE
      ,DSC_TIPO_INTERNACAO
      ,FLG_ORIGEM_PS
      ,FLG_COVID
      ,FLG_DIARIA_UTI_GERAL
    
      ,FLG_DIARIA_PARTO_UTI_NEONATAL
      ,FLG_DIARIA_PARTO_UTI_ADULTO
      ,FLG_DIARIA_PARTO_UTI_GERAL
      
      ,FLG_INTERCORRENCIA
      ,FLG_REINTERNACAO_QUALQUER_PRESTADOR
      ,FLG_REINTERNACAO_MESMO_PRESTADOR
      ,DSC_CARATER_ATENDIMENTO_INTERNACAO 
      ,COD_PRINCIPAL_SERVICO
      ,COUNT(NUM_INTERNACAO) QTD_INTERNACAO
      ,SUM(VLR_PAGO_INTERNACAO_TOTAL) AS VLR_PAGO_INTERNACAO_TOTAL
      ,SUM(VAL_CUSTO_HONORARIO_MEDICO) AS VAL_CUSTO_HONORARIO_MEDICO
      ,SUM(VAL_CUSTO_HOSPITALAR) AS VAL_CUSTO_HOSPITALAR
      ,SUM(VAL_CUSTO_MATERIAL) AS VAL_CUSTO_MATERIAL
      ,SUM(VAL_CUSTO_MEDICAMENTO) AS VAL_CUSTO_MEDICAMENTO
      ,SUM(QTD_PAGO_DIARIA_UTI_GERAL) AS QTD_PAGO_DIARIA_UTI_GERAL
      ,SUM(QTD_DIAS_INTERNADO) AS QTD_DIAS_INTERNADO
  FROM CTE_INTERNACAO      
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
--------------------------------CRIA A BASE DE INTERNACAO------------------------------------



CREATE OR REPLACE TABLE SANDBOX_GERAC.LT_GT_SINISTRO_BASE_TOTAL_INTERNACOES2_TESTE 
OPTIONS (
    EXPIRATION_TIMESTAMP=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 10 DAY)
)
AS 
SELECT

    
    DSC_FAIXA_ETARIA,

    NUM_ANO_INTERNACAO ANO
  , SUBSTR(NUM_ANO_MES_INTERNACAO, 5, 7) MES
  , NUM_ANO_MES_INTERNACAO ANO_MES
  , 'CIRURGICA' AS BASE
  , P.NME_PRESTADOR
  , P.NME_GRUPO_ECONOMICO_PRESTADOR
  , P.DSC_CLASSIFICACAO_PRESTADOR

  , P.SIG_UF_PRESTADOR


  , COD_ANALITICO_BENEFICIARIO
  , NME_PLANO
  , NME_PLANO_AJUSTADO
  , DSC_CARTEIRA
  , FLG_ORIGEM_PS
  , FLG_COVID
  , QTD_INTERNACAO
  , QTD_DIAS_INTERNADO
  , VAL_CUSTO_HONORARIO_MEDICO
  , VAL_CUSTO_HOSPITALAR
  , VAL_CUSTO_MATERIAL
  , VAL_CUSTO_MEDICAMENTO
  , VLR_PAGO_INTERNACAO_TOTAL
    
  ,FLG_DIARIA_UTI_GERAL
  ,FLG_DIARIA_PARTO_UTI_NEONATAL
  ,FLG_DIARIA_PARTO_UTI_ADULTO
  ,FLG_DIARIA_PARTO_UTI_GERAL

FROM self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_CIRURGICA_ANALITICA_LA_TESTE
LEFT JOIN self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO P 
  USING(COD_PRESTADOR)


UNION ALL

SELECT

     
    DSC_FAIXA_ETARIA,

  
  NUM_ANO_INTERNACAO ANO
  , SUBSTR(NUM_ANO_MES_INTERNACAO, 5, 7) MES
  , NUM_ANO_MES_INTERNACAO ANO_MES
  , 'CLINICA' AS BASE
  , P.NME_PRESTADOR
  , P.NME_GRUPO_ECONOMICO_PRESTADOR
  , P.DSC_CLASSIFICACAO_PRESTADOR
  
  , P.SIG_UF_PRESTADOR


  , COD_ANALITICO_BENEFICIARIO
  , NME_PLANO
  , NME_PLANO_AJUSTADO
  , DSC_CARTEIRA
  , FLG_ORIGEM_PS
  , FLG_COVID
  , QTD_INTERNACAO
  , QTD_DIAS_INTERNADO
  , VAL_CUSTO_HONORARIO_MEDICO
  , VAL_CUSTO_HOSPITALAR
  , VAL_CUSTO_MATERIAL
  , VAL_CUSTO_MEDICAMENTO
  , VLR_PAGO_INTERNACAO_TOTAL
    
  ,FLG_DIARIA_UTI_GERAL
  ,FLG_DIARIA_PARTO_UTI_NEONATAL
  ,FLG_DIARIA_PARTO_UTI_ADULTO
  ,FLG_DIARIA_PARTO_UTI_GERAL

FROM self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_CLINICA_ANALITICA_LA_TESTE
LEFT JOIN self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO P 
  USING(COD_PRESTADOR)

UNION ALL 
SELECT

     
    DSC_FAIXA_ETARIA,

  
  NUM_ANO_INTERNACAO ANO
  , SUBSTR(NUM_ANO_MES_INTERNACAO, 5, 7) MES
  , NUM_ANO_MES_INTERNACAO ANO_MES
  , 'DOMICILIAR' AS BASE
  , P.NME_PRESTADOR
  , P.NME_GRUPO_ECONOMICO_PRESTADOR
  , P.DSC_CLASSIFICACAO_PRESTADOR
    
  , P.SIG_UF_PRESTADOR


  , COD_ANALITICO_BENEFICIARIO
  , NME_PLANO
  , NME_PLANO_AJUSTADO
  , DSC_CARTEIRA
  , FLG_ORIGEM_PS
  , FLG_COVID
  , QTD_INTERNACAO
  , QTD_DIAS_INTERNADO
  , VAL_CUSTO_HONORARIO_MEDICO
  , VAL_CUSTO_HOSPITALAR
  , VAL_CUSTO_MATERIAL
  , VAL_CUSTO_MEDICAMENTO
  , VLR_PAGO_INTERNACAO_TOTAL
    
  ,FLG_DIARIA_UTI_GERAL
  ,FLG_DIARIA_PARTO_UTI_NEONATAL
  ,FLG_DIARIA_PARTO_UTI_ADULTO
  ,FLG_DIARIA_PARTO_UTI_GERAL

FROM self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_DOMICILIAR_ANALITICA_LA_TESTE
LEFT JOIN self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO P 
  USING(COD_PRESTADOR)

UNION ALL 
SELECT

     
    DSC_FAIXA_ETARIA,

  
  NUM_ANO_INTERNACAO ANO
  , SUBSTR(NUM_ANO_MES_INTERNACAO, 5, 7) MES
  , NUM_ANO_MES_INTERNACAO ANO_MES
  , 'PARTO' AS BASE
  , P.NME_PRESTADOR
  , P.NME_GRUPO_ECONOMICO_PRESTADOR
  , P.DSC_CLASSIFICACAO_PRESTADOR
    
  , P.SIG_UF_PRESTADOR


  , COD_ANALITICO_BENEFICIARIO
  , NME_PLANO
  , NME_PLANO_AJUSTADO
  , DSC_CARTEIRA
  , FLG_ORIGEM_PS
  , FLG_COVID
  , QTD_INTERNACAO
  , QTD_DIAS_INTERNADO
  , VAL_CUSTO_HONORARIO_MEDICO
  , VAL_CUSTO_HOSPITALAR
  , VAL_CUSTO_MATERIAL
  , VAL_CUSTO_MEDICAMENTO
  , VLR_PAGO_INTERNACAO_TOTAL
    
  ,FLG_DIARIA_UTI_GERAL
  ,FLG_DIARIA_PARTO_UTI_NEONATAL
  ,FLG_DIARIA_PARTO_UTI_ADULTO
  ,FLG_DIARIA_PARTO_UTI_GERAL

FROM self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_PARTO_ANALITICA_LA_TESTE
LEFT JOIN self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO P 
  USING(COD_PRESTADOR)

UNION ALL 
SELECT

   
    DSC_FAIXA_ETARIA,

  
  NUM_ANO_INTERNACAO ANO
  , SUBSTR(NUM_ANO_MES_INTERNACAO, 5, 7) MES
  , NUM_ANO_MES_INTERNACAO ANO_MES
  , 'PSIQUIATRICA' AS BASE
  , P.NME_PRESTADOR
  , P.NME_GRUPO_ECONOMICO_PRESTADOR
  , P.DSC_CLASSIFICACAO_PRESTADOR
    
  , P.SIG_UF_PRESTADOR

  , COD_ANALITICO_BENEFICIARIO
  , NME_PLANO
  , NME_PLANO_AJUSTADO
  , DSC_CARTEIRA
  , FLG_ORIGEM_PS
  , FLG_COVID
  , QTD_INTERNACAO
  , QTD_DIAS_INTERNADO
  , VAL_CUSTO_HONORARIO_MEDICO
  , VAL_CUSTO_HOSPITALAR
  , VAL_CUSTO_MATERIAL
  , VAL_CUSTO_MEDICAMENTO
  , VLR_PAGO_INTERNACAO_TOTAL

    
  ,FLG_DIARIA_UTI_GERAL
  ,FLG_DIARIA_PARTO_UTI_NEONATAL
  ,FLG_DIARIA_PARTO_UTI_ADULTO
  ,FLG_DIARIA_PARTO_UTI_GERAL

FROM self-service-saude.SANDBOX_GERAC.TB_GT_SINISTRO_COMPETENCIA_PSIQUIATRICA_ANALITICA_LA_TESTE
LEFT JOIN self-service-saude-prd.REF_SAUDE_PRESTADOR_REFERENCIADO.TB_CAD_PRESTADOR_REFERENCIADO P 
  USING(COD_PRESTADOR)
;
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
--CRIA BASE INTERNACAO COM OS CALCULOS DE VARIAÇÃO PARA USAR NO PAINEL DO DATA STUDIO----------------


#OBS IMPORTANTE...APÓS CRIADA DEVE-SE ARRUMAR EM DSC_CARTEIRA ASO PARA ADMINISTRADO E ADESÃO PARA ADESAO

CREATE OR REPLACE TABLE SANDBOX_GERAC.LT_GT_SINISTRO_BASE_TOTAL_INTERNACOES_ANALISE_DOR_DATASTUDIO_TESTE 
OPTIONS (
    EXPIRATION_TIMESTAMP=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 10 DAY)
)
AS

WITH TABELA2 AS 
(
#PRIMEIRO SELECT,SELECIONA APENAS ALGUNS PLANOLS DA BASE DE INTERNAÇÃO
WITH TABELA1 AS   
    (
    SELECT
    DSC_FAIXA_ETARIA,
     SIG_UF_PRESTADOR,

  ANO
  , MES
  , ANO_MES
  , BASE 
  , CASE 
      WHEN DSC_CARTEIRA = 'ASO' THEN 'ADMINISTRADO' 
      WHEN DSC_CARTEIRA = 'ADESÃO' THEN 'ADESAO' 
      ELSE DSC_CARTEIRA 
    END AS DSC_CARTEIRA
  , NME_PLANO_AJUSTADO
  , FLG_ORIGEM_PS
  , FLG_COVID
  
    
  ,FLG_DIARIA_UTI_GERAL
  ,FLG_DIARIA_PARTO_UTI_NEONATAL
  ,FLG_DIARIA_PARTO_UTI_ADULTO
  ,FLG_DIARIA_PARTO_UTI_GERAL

  , SUM(QTD_INTERNACAO) AS TOTAL_QUANTIDADE
  , SUM(QTD_DIAS_INTERNADO) AS TOTAL_DIAS_INTERNADO
  , SUM(VAL_CUSTO_HONORARIO_MEDICO) AS TOTAL_CUSTO_HM
  , SUM(VAL_CUSTO_HOSPITALAR) AS TOTAL_CUSTO_HOSPITALAR
  , SUM(VAL_CUSTO_MATERIAL) AS TOTAL_CUSTO_MATERIAL
  , SUM(VAL_CUSTO_MEDICAMENTO) AS TOTAL_CUSTO_MEDICAMENTOS 
  , SUM(VLR_PAGO_INTERNACAO_TOTAL) AS TOTAL_SINISTRO
  , COUNT(DISTINCT COD_ANALITICO_BENEFICIARIO) AS SINISTRADOS
  
FROM SANDBOX_GERAC.LT_GT_SINISTRO_BASE_TOTAL_INTERNACOES2_TESTE

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14
    )




SELECT 
    DSC_FAIXA_ETARIA,
     SIG_UF_PRESTADOR,

  ANO
  , MES
  , ANO_MES
  , BASE 
  , DSC_CARTEIRA
  , NME_PLANO_AJUSTADO
  , FLG_ORIGEM_PS
  , FLG_COVID
  
    
  ,FLG_DIARIA_UTI_GERAL
  ,FLG_DIARIA_PARTO_UTI_NEONATAL
  ,FLG_DIARIA_PARTO_UTI_ADULTO
  ,FLG_DIARIA_PARTO_UTI_GERAL,

  #, SUM(QTD_INTERNACAO) AS TOTAL_QUANTIDADE,
  #, SUM(QTD_DIAS_INTERNADO) AS TOTAL_DIAS_INTERNADO
  #, SUM(VAL_CUSTO_HONORARIO_MEDICO) AS TOTAL_CUSTO_HM
  #, SUM(VAL_CUSTO_HOSPITALAR) AS TOTAL_CUSTO_HOSPITALAR
  #, SUM(VAL_CUSTO_MATERIAL) AS TOTAL_CUSTO_MATERIAL
  #, SUM(VAL_CUSTO_MEDICAMENTO) AS TOTAL_CUSTO_MEDICAMENTOS 
  #, SUM(VLR_PAGO_INTERNACAO_TOTAL) AS TOTAL_SINISTRO
  #, COUNT(DISTINCT COD_ANALITICO_BENEFICIARIO) AS SINISTRADOS,

#TOTAL_QUANTIDADE
CASE WHEN ANO = '2018' THEN TOTAL_QUANTIDADE ELSE 0 END AS TOTAL_QUANTIDADE_2018,
CASE WHEN ANO = '2019' THEN TOTAL_QUANTIDADE ELSE 0 END AS TOTAL_QUANTIDADE_2019,
CASE WHEN ANO = '2020' THEN TOTAL_QUANTIDADE ELSE 0 END AS TOTAL_QUANTIDADE_2020,
CASE WHEN ANO = '2021' THEN TOTAL_QUANTIDADE ELSE 0 END AS TOTAL_QUANTIDADE_2021,
CASE WHEN ANO = '2022' THEN TOTAL_QUANTIDADE ELSE 0 END AS TOTAL_QUANTIDADE_2022,

#TOTAL_DIAS_INTERNADO
CASE WHEN ANO = '2018' THEN TOTAL_DIAS_INTERNADO ELSE 0 END AS TOTAL_DIAS_INTERNADO_2018,
CASE WHEN ANO = '2019' THEN TOTAL_DIAS_INTERNADO ELSE 0 END AS TOTAL_DIAS_INTERNADO_2019,
CASE WHEN ANO = '2020' THEN TOTAL_DIAS_INTERNADO ELSE 0 END AS TOTAL_DIAS_INTERNADO_2020,
CASE WHEN ANO = '2021' THEN TOTAL_DIAS_INTERNADO ELSE 0 END AS TOTAL_DIAS_INTERNADO_2021,
CASE WHEN ANO = '2022' THEN TOTAL_DIAS_INTERNADO ELSE 0 END AS TOTAL_DIAS_INTERNADO_2022,

#TOTAL_CUSTO_HM
CASE WHEN ANO = '2018' THEN TOTAL_CUSTO_HM ELSE 0 END AS TOTAL_CUSTO_HM_2018,
CASE WHEN ANO = '2019' THEN TOTAL_CUSTO_HM ELSE 0 END AS TOTAL_CUSTO_HM_2019,
CASE WHEN ANO = '2020' THEN TOTAL_CUSTO_HM ELSE 0 END AS TOTAL_CUSTO_HM_2020,
CASE WHEN ANO = '2021' THEN TOTAL_CUSTO_HM ELSE 0 END AS TOTAL_CUSTO_HM_2021,
CASE WHEN ANO = '2022' THEN TOTAL_CUSTO_HM ELSE 0 END AS TOTAL_CUSTO_HM_2022,

#TOTAL_CUSTO_HOSPITALAR
CASE WHEN ANO = '2018' THEN TOTAL_CUSTO_HOSPITALAR ELSE 0 END AS TOTAL_CUSTO_HOSPITALAR_2018,
CASE WHEN ANO = '2019' THEN TOTAL_CUSTO_HOSPITALAR ELSE 0 END AS TOTAL_CUSTO_HOSPITALAR_2019,
CASE WHEN ANO = '2020' THEN TOTAL_CUSTO_HOSPITALAR ELSE 0 END AS TOTAL_CUSTO_HOSPITALAR_2020,
CASE WHEN ANO = '2021' THEN TOTAL_CUSTO_HOSPITALAR ELSE 0 END AS TOTAL_CUSTO_HOSPITALAR_2021,
CASE WHEN ANO = '2022' THEN TOTAL_CUSTO_HOSPITALAR ELSE 0 END AS TOTAL_CUSTO_HOSPITALAR_2022,

#TOTAL_CUSTO_MATERIAL
CASE WHEN ANO = '2018' THEN TOTAL_CUSTO_MATERIAL ELSE 0 END AS TOTAL_CUSTO_MATERIAL_2018,
CASE WHEN ANO = '2019' THEN TOTAL_CUSTO_MATERIAL ELSE 0 END AS TOTAL_CUSTO_MATERIAL_2019,
CASE WHEN ANO = '2020' THEN TOTAL_CUSTO_MATERIAL ELSE 0 END AS TOTAL_CUSTO_MATERIAL_2020,
CASE WHEN ANO = '2021' THEN TOTAL_CUSTO_MATERIAL ELSE 0 END AS TOTAL_CUSTO_MATERIAL_2021,
CASE WHEN ANO = '2022' THEN TOTAL_CUSTO_MATERIAL ELSE 0 END AS TOTAL_CUSTO_MATERIAL_2022,

#TOTAL_CUSTO_MEDICAMENTOS
CASE WHEN ANO = '2018' THEN TOTAL_CUSTO_MEDICAMENTOS ELSE 0 END AS TOTAL_CUSTO_MEDICAMENTOS_2018,
CASE WHEN ANO = '2019' THEN TOTAL_CUSTO_MEDICAMENTOS ELSE 0 END AS TOTAL_CUSTO_MEDICAMENTOS_2019,
CASE WHEN ANO = '2020' THEN TOTAL_CUSTO_MEDICAMENTOS ELSE 0 END AS TOTAL_CUSTO_MEDICAMENTOS_2020,
CASE WHEN ANO = '2021' THEN TOTAL_CUSTO_MEDICAMENTOS ELSE 0 END AS TOTAL_CUSTO_MEDICAMENTOS_2021,
CASE WHEN ANO = '2022' THEN TOTAL_CUSTO_MEDICAMENTOS ELSE 0 END AS TOTAL_CUSTO_MEDICAMENTOS_2022,

#TOTAL_SINISTRO
CASE WHEN ANO = '2018' THEN TOTAL_SINISTRO ELSE 0 END AS TOTAL_SINISTRO_2018,
CASE WHEN ANO = '2019' THEN TOTAL_SINISTRO ELSE 0 END AS TOTAL_SINISTRO_2019,
CASE WHEN ANO = '2020' THEN TOTAL_SINISTRO ELSE 0 END AS TOTAL_SINISTRO_2020,
CASE WHEN ANO = '2021' THEN TOTAL_SINISTRO ELSE 0 END AS TOTAL_SINISTRO_2021,
CASE WHEN ANO = '2022' THEN TOTAL_SINISTRO ELSE 0 END AS TOTAL_SINISTRO_2022,

#SINISTRADOS
CASE WHEN ANO = '2018' THEN SINISTRADOS ELSE 0 END AS SINISTRADOS_2018,
CASE WHEN ANO = '2019' THEN SINISTRADOS ELSE 0 END AS SINISTRADOS_2019,
CASE WHEN ANO = '2020' THEN SINISTRADOS ELSE 0 END AS SINISTRADOS_2020,
CASE WHEN ANO = '2021' THEN SINISTRADOS ELSE 0 END AS SINISTRADOS_2021,
CASE WHEN ANO = '2022' THEN SINISTRADOS ELSE 0 END AS SINISTRADOS_2022

FROM TABELA1

)
SELECT 
    DSC_FAIXA_ETARIA,
     SIG_UF_PRESTADOR,

  ANO
  , MES
  , ANO_MES
  , BASE 
  , DSC_CARTEIRA
  , NME_PLANO_AJUSTADO
  , FLG_ORIGEM_PS
  , FLG_COVID

    
  ,FLG_DIARIA_UTI_GERAL
  ,FLG_DIARIA_PARTO_UTI_NEONATAL
  ,FLG_DIARIA_PARTO_UTI_ADULTO
  ,FLG_DIARIA_PARTO_UTI_GERAL,

SUM(TOTAL_QUANTIDADE_2018) AS TOTAL_QUANTIDADE_2018,
SUM(TOTAL_QUANTIDADE_2019) AS TOTAL_QUANTIDADE_2019,
SUM(TOTAL_QUANTIDADE_2020) AS TOTAL_QUANTIDADE_2020,
SUM(TOTAL_QUANTIDADE_2021) AS TOTAL_QUANTIDADE_2021,
SUM(TOTAL_QUANTIDADE_2022) AS TOTAL_QUANTIDADE_2022,

SUM(TOTAL_DIAS_INTERNADO_2018) AS TOTAL_DIAS_INTERNADO_2018,
SUM(TOTAL_DIAS_INTERNADO_2019) AS TOTAL_DIAS_INTERNADO_2019,
SUM(TOTAL_DIAS_INTERNADO_2020) AS TOTAL_DIAS_INTERNADO_2020,
SUM(TOTAL_DIAS_INTERNADO_2021) AS TOTAL_DIAS_INTERNADO_2021,
SUM(TOTAL_DIAS_INTERNADO_2022) AS TOTAL_DIAS_INTERNADO_2022,

SUM(TOTAL_CUSTO_HM_2018) AS TOTAL_CUSTO_HM_2018,
SUM(TOTAL_CUSTO_HM_2019) AS TOTAL_CUSTO_HM_2019,
SUM(TOTAL_CUSTO_HM_2020) AS TOTAL_CUSTO_HM_2020,
SUM(TOTAL_CUSTO_HM_2021) AS TOTAL_CUSTO_HM_2021,
SUM(TOTAL_CUSTO_HM_2022) AS TOTAL_CUSTO_HM_2022,

SUM(TOTAL_CUSTO_HOSPITALAR_2018) AS TOTAL_CUSTO_HOSPITALAR_2018,
SUM(TOTAL_CUSTO_HOSPITALAR_2019) AS TOTAL_CUSTO_HOSPITALAR_2019,
SUM(TOTAL_CUSTO_HOSPITALAR_2020) AS TOTAL_CUSTO_HOSPITALAR_2020,
SUM(TOTAL_CUSTO_HOSPITALAR_2021) AS TOTAL_CUSTO_HOSPITALAR_2021,
SUM(TOTAL_CUSTO_HOSPITALAR_2022) AS TOTAL_CUSTO_HOSPITALAR_2022,

SUM(TOTAL_CUSTO_MATERIAL_2018) AS TOTAL_CUSTO_MATERIAL_2018,
SUM(TOTAL_CUSTO_MATERIAL_2019) AS TOTAL_CUSTO_MATERIAL_2019,
SUM(TOTAL_CUSTO_MATERIAL_2020) AS TOTAL_CUSTO_MATERIAL_2020,
SUM(TOTAL_CUSTO_MATERIAL_2021) AS TOTAL_CUSTO_MATERIAL_2021,
SUM(TOTAL_CUSTO_MATERIAL_2022) AS TOTAL_CUSTO_MATERIAL_2022,

SUM(TOTAL_CUSTO_MEDICAMENTOS_2018) AS TOTAL_CUSTO_MEDICAMENTOS_2018,
SUM(TOTAL_CUSTO_MEDICAMENTOS_2019) AS TOTAL_CUSTO_MEDICAMENTOS_2019,
SUM(TOTAL_CUSTO_MEDICAMENTOS_2020) AS TOTAL_CUSTO_MEDICAMENTOS_2020,
SUM(TOTAL_CUSTO_MEDICAMENTOS_2021) AS TOTAL_CUSTO_MEDICAMENTOS_2021,
SUM(TOTAL_CUSTO_MEDICAMENTOS_2022) AS TOTAL_CUSTO_MEDICAMENTOS_2022,

SUM(TOTAL_SINISTRO_2018) AS TOTAL_SINISTRO_2018,
SUM(TOTAL_SINISTRO_2019) AS TOTAL_SINISTRO_2019,
SUM(TOTAL_SINISTRO_2020) AS TOTAL_SINISTRO_2020,
SUM(TOTAL_SINISTRO_2021) AS TOTAL_SINISTRO_2021,
SUM(TOTAL_SINISTRO_2022) AS TOTAL_SINISTRO_2022,

SUM(SINISTRADOS_2018) AS SINISTRADOS_2018,
SUM(SINISTRADOS_2019) AS SINISTRADOS_2019,
SUM(SINISTRADOS_2020) AS SINISTRADOS_2020,
SUM(SINISTRADOS_2021) AS SINISTRADOS_2021,
SUM(SINISTRADOS_2022) AS SINISTRADOS_2022,

-- VAR ABS QTD ATENDIMENTO 
SUM(TOTAL_QUANTIDADE_2019) - SUM(TOTAL_QUANTIDADE_2018) AS VAR_ABS_TOTAL_QUANTIDADE_19_18,
SUM(TOTAL_QUANTIDADE_2020) - SUM(TOTAL_QUANTIDADE_2019) AS VAR_ABS_TOTAL_QUANTIDADE_20_19,
SUM(TOTAL_QUANTIDADE_2021) - SUM(TOTAL_QUANTIDADE_2020) AS VAR_ABS_TOTAL_QUANTIDADE_21_20,
SUM(TOTAL_QUANTIDADE_2022) - SUM(TOTAL_QUANTIDADE_2021) AS VAR_ABS_TOTAL_QUANTIDADE_22_21,
SUM(TOTAL_QUANTIDADE_2022) - SUM(TOTAL_QUANTIDADE_2019) AS VAR_ABS_TOTAL_QUANTIDADE_22_19,

-- VAR ABS DIAS_INTERNADO
SUM(TOTAL_DIAS_INTERNADO_2019) - SUM(TOTAL_DIAS_INTERNADO_2018) AS VAR_ABS_TOTAL_DIAS_INTERNADO_19_18,
SUM(TOTAL_DIAS_INTERNADO_2020) - SUM(TOTAL_DIAS_INTERNADO_2019) AS VAR_ABS_TOTAL_DIAS_INTERNADO_20_19,
SUM(TOTAL_DIAS_INTERNADO_2021) - SUM(TOTAL_DIAS_INTERNADO_2020) AS VAR_ABS_TOTAL_DIAS_INTERNADO_21_20,
SUM(TOTAL_DIAS_INTERNADO_2022) - SUM(TOTAL_DIAS_INTERNADO_2021) AS VAR_ABS_TOTAL_DIAS_INTERNADO_22_21,
SUM(TOTAL_DIAS_INTERNADO_2022) - SUM(TOTAL_DIAS_INTERNADO_2019) AS VAR_ABS_TOTAL_DIAS_INTERNADO_22_19,


-- VAR ABS CUSTO_HM
SUM(TOTAL_CUSTO_HM_2019) - SUM(TOTAL_CUSTO_HM_2018) AS VAR_ABS_TOTAL_CUSTO_HM_19_18,
SUM(TOTAL_CUSTO_HM_2020) - SUM(TOTAL_CUSTO_HM_2019) AS VAR_ABS_TOTAL_CUSTO_HM_20_19,
SUM(TOTAL_CUSTO_HM_2021) - SUM(TOTAL_CUSTO_HM_2020) AS VAR_ABS_TOTAL_CUSTO_HM_21_20,
SUM(TOTAL_CUSTO_HM_2022) - SUM(TOTAL_CUSTO_HM_2021) AS VAR_ABS_TOTAL_CUSTO_HM_22_21,
SUM(TOTAL_CUSTO_HM_2022) - SUM(TOTAL_CUSTO_HM_2019) AS VAR_ABS_TOTAL_CUSTO_HM_22_19,


-- VAR CUSTO_HOSPITALAR
SUM(TOTAL_CUSTO_HOSPITALAR_2019) - SUM(TOTAL_CUSTO_HOSPITALAR_2018) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_19_18,
SUM(TOTAL_CUSTO_HOSPITALAR_2020) - SUM(TOTAL_CUSTO_HOSPITALAR_2019) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_20_19,
SUM(TOTAL_CUSTO_HOSPITALAR_2021) - SUM(TOTAL_CUSTO_HOSPITALAR_2020) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_21_20,
SUM(TOTAL_CUSTO_HOSPITALAR_2022) - SUM(TOTAL_CUSTO_HOSPITALAR_2021) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_22_21,
SUM(TOTAL_CUSTO_HOSPITALAR_2022) - SUM(TOTAL_CUSTO_HOSPITALAR_2019) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_22_19,


-- VAR ABS CUSTO_MATERIAL
SUM(TOTAL_CUSTO_MATERIAL_2019) - SUM(TOTAL_CUSTO_MATERIAL_2018) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_19_18,
SUM(TOTAL_CUSTO_MATERIAL_2020) - SUM(TOTAL_CUSTO_MATERIAL_2019) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_20_19,
SUM(TOTAL_CUSTO_MATERIAL_2021) - SUM(TOTAL_CUSTO_MATERIAL_2020) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_21_20,
SUM(TOTAL_CUSTO_MATERIAL_2022) - SUM(TOTAL_CUSTO_MATERIAL_2021) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_22_21,
SUM(TOTAL_CUSTO_MATERIAL_2022) - SUM(TOTAL_CUSTO_MATERIAL_2019) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_22_19,

-- VAR ABS CUSTO_MEDICAMENTOS
SUM(TOTAL_CUSTO_MEDICAMENTOS_2019) - SUM(TOTAL_CUSTO_MEDICAMENTOS_2018) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_19_18,
SUM(TOTAL_CUSTO_MEDICAMENTOS_2020) - SUM(TOTAL_CUSTO_MEDICAMENTOS_2019) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_20_19,
SUM(TOTAL_CUSTO_MEDICAMENTOS_2021) - SUM(TOTAL_CUSTO_MEDICAMENTOS_2020) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_21_20,
SUM(TOTAL_CUSTO_MEDICAMENTOS_2022) - SUM(TOTAL_CUSTO_MEDICAMENTOS_2021) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_22_21,
SUM(TOTAL_CUSTO_MEDICAMENTOS_2022) - SUM(TOTAL_CUSTO_MEDICAMENTOS_2019) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_22_19,

-- VAR ABS TOTAL SINISTRO
SUM(TOTAL_SINISTRO_2019) - SUM(TOTAL_SINISTRO_2018) AS VAR_ABS_TOTAL_SINISTRO_19_18,
SUM(TOTAL_SINISTRO_2020) - SUM(TOTAL_SINISTRO_2019) AS VAR_ABS_TOTAL_SINISTRO_20_19,
SUM(TOTAL_SINISTRO_2021) - SUM(TOTAL_SINISTRO_2020) AS VAR_ABS_TOTAL_SINISTRO_21_20,
SUM(TOTAL_SINISTRO_2022) - SUM(TOTAL_SINISTRO_2021) AS VAR_ABS_TOTAL_SINISTRO_22_21,
SUM(TOTAL_SINISTRO_2022) - SUM(TOTAL_SINISTRO_2019) AS VAR_ABS_TOTAL_SINISTRO_22_19,


-- VAR ABS QTD SINISTRADOS

SUM(SINISTRADOS_2019) - SUM(SINISTRADOS_2018) AS VAR_ABS_SINISTRADOS_19_18,
SUM(SINISTRADOS_2020) - SUM(SINISTRADOS_2019) AS VAR_ABS_SINISTRADOS_20_19,
SUM(SINISTRADOS_2021) - SUM(SINISTRADOS_2020) AS VAR_ABS_SINISTRADOS_21_20,
SUM(SINISTRADOS_2022) - SUM(SINISTRADOS_2021) AS VAR_ABS_SINISTRADOS_22_21,
SUM(SINISTRADOS_2022) - SUM(SINISTRADOS_2019) AS VAR_ABS_SINISTRADOS_22_19

FROM TABELA2
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14


;
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------



--OBSERVAÇÃO IMPORTANTE: NA BASE DE EXPOSTOS, QUE É CRIADA PRIMEIRO NO EXCEL, DEPOIS SUBIMOS PARA O BIGQUERY,
--EXISTE O CÁLCULO DE DE PESO, QUE CALCULA O PERCENTUAL DE EXPOSTOS DE CADA PLANO EM RELAÇÃO 
--AO TOTAL DE EXPOSTOS NAQUELE ANO E NAQUELE MÊS.

--A PHANILHA DO EXCEL ONDE GERAMOS O PESO FICA NO ENDEREÇO C:\Users\la165808\Documents\ATUALIZAÇÃO 
--INDICADORES\EXPOSTOS FINAL2.XLSX.

--DENTRO DO PAINEL DO DATASTUDIO FAZEMOS A JUNÇÃO DA BASE AMBULATORIAL E DA BASE DE INTERNAÇÃO
--COM A COLUNA DE PESO DA PLANILHA DE EXPOSTOS, A CHAVE USADA É A CONCATENAÇÃO DE ANO, MES, CARTEIRA E PLANO

--NA PLANILHA DE EXPOSTOS EXISTEM CHAVES QUE NÃO TEM NAS PLANILHAS AMBULATORIAL E INTERNAÇÃO, POR ISSO,
--INCLUÍMOS NESSAS PLANILHAS TOS OS ANO, MES, CARTEIRA E PLANOS QUE TEM NA BASE DE EXPOSTOS E NÃO TEM NAS
--BASES DE FATURAMENTO AMBULATORIAL E INT.

--PARA REALIZAR ESSA INCLUSÃO CRIAMOS O ARQUIVO ABAIXO
--C:\Users\la165808\Documents\ATUALIZAÇÃO INDICADORES\inclusao anomescartplano.XLSX
--O MESMO POSSUI UMA ABA COM TODAS AS COLUNAS DA BASE AMBULATORIAL, E OUTRA COM AS DA INTERNAÇÃO,
--PORÉM, TODAS AS COLUNAS SÃO VAZIAS, EXCETO ANO, MES, CARTEIRA E PLANO

--DEPOIS DE CRIAR ESSE ARQUIVO, FAZEMOS O UNION ALL DA BASE AMBULATORIAL E INT COM ESSE ARQUIVO,
--PARA QUE ESSAS BASES CONTENHA TODAS AS CHAVES QUE EXISTE NA PLANILHA DE EXPOSTOS

--ABAIXO A QUERIE PARA REALZAR ESSA JUNÇÃO INTERNACAO


------------UNION PARA INCLUIR ANOMESCARTPLANO NA BASE INTERNACAO------------------------------------
CREATE OR REPLACE TABLE SANDBOX_GERAC.LT_GT_SINISTRO_BASE_TOTAL_INTERNACOES_ANALISE_DOR_DATASTUDIO_TESTE 
OPTIONS (
    EXPIRATION_TIMESTAMP=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 10 DAY)
)
AS

WITH ANOMESCARTPLANO AS(
#---------------------------------------------------------------------------------------------------------------------------
#SELECIONA TODOS OS ANOMESCARTPLANO QUE TEM NA TABELA EXPOSTOS E NÃO TEM NA TABELA INTERNADOS
WITH A AS
(SELECT DISTINCT
ANO,MES,ANO_MES,DSC_CARTEIRA,NME_PLANO_AJUSTADO,CONCAT(ANO_MES,DSC_CARTEIRA,NME_PLANO_AJUSTADO) AS CHAVE
FROM SANDBOX_GERAC.LT_GT_SINISTRO_BASE_TOTAL_INTERNACOES_ANALISE_DOR_DATASTUDIO_TESTE) 

SELECT 
B.*

FROM A TAB

RIGHT JOIN

(SELECT DISTINCT ANO,MES,ANO_MES,CARTEIRA,PLANO,CONCAT(ANO_MES,CARTEIRA,PLANO) AS CHAVE FROM SANDBOX_GERAC.TB_EXPOSTOS_FINAL_LA WHERE PLANO IS NOT NULL) B

USING(CHAVE)

WHERE TAB.CHAVE IS NULL
#---------------------------------------------------------------------------------------------------------------------------
)

SELECT  
CAST(NULL AS STRING) AS DSC_FAIXA_ETARIA,
CAST(NULL AS STRING) AS SIG_UF_PRESTADOR,
CAST(ANO AS STRING) AS ANO,
CAST(MES AS STRING) AS MES,
CAST(ANO_MES AS STRING) AS ANO_MES,
CAST(NULL AS STRING) AS BASE,
CAST(CARTEIRA AS STRING) AS DSC_CARTEIRA,
CAST(PLANO AS STRING) AS NME_PLANO_AJUSTADO,
CAST(NULL AS STRING) AS FLG_ORIGEM_PS,
CAST(NULL AS STRING) AS FLG_COVID,
CAST(NULL AS STRING) AS FLG_DIARIA_UTI_GERAL,
CAST(NULL AS STRING) AS FLG_DIARIA_PARTO_UTI_NEONATAL,
CAST(NULL AS STRING) AS FLG_DIARIA_PARTO_UTI_ADULTO,
CAST(NULL AS STRING) AS FLG_DIARIA_PARTO_UTI_GERAL,
CAST(NULL AS INTEGER) AS TOTAL_QUANTIDADE_2018,
CAST(NULL AS INTEGER) AS TOTAL_QUANTIDADE_2019,
CAST(NULL AS INTEGER) AS TOTAL_QUANTIDADE_2020,
CAST(NULL AS INTEGER) AS TOTAL_QUANTIDADE_2021,
CAST(NULL AS INTEGER) AS TOTAL_QUANTIDADE_2022,
CAST(NULL AS INTEGER) AS TOTAL_DIAS_INTERNADO_2018,
CAST(NULL AS INTEGER) AS TOTAL_DIAS_INTERNADO_2019,
CAST(NULL AS INTEGER) AS TOTAL_DIAS_INTERNADO_2020,
CAST(NULL AS INTEGER) AS TOTAL_DIAS_INTERNADO_2021,
CAST(NULL AS INTEGER) AS TOTAL_DIAS_INTERNADO_2022,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HM_2018,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HM_2019,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HM_2020,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HM_2021,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HM_2022,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HOSPITALAR_2018,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HOSPITALAR_2019,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HOSPITALAR_2020,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HOSPITALAR_2021,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_HOSPITALAR_2022,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MATERIAL_2018,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MATERIAL_2019,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MATERIAL_2020,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MATERIAL_2021,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MATERIAL_2022,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MEDICAMENTOS_2018,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MEDICAMENTOS_2019,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MEDICAMENTOS_2020,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MEDICAMENTOS_2021,
CAST(NULL AS NUMERIC) AS TOTAL_CUSTO_MEDICAMENTOS_2022,
CAST(NULL AS NUMERIC) AS TOTAL_SINISTRO_2018,
CAST(NULL AS NUMERIC) AS TOTAL_SINISTRO_2019,
CAST(NULL AS NUMERIC) AS TOTAL_SINISTRO_2020,
CAST(NULL AS NUMERIC) AS TOTAL_SINISTRO_2021,
CAST(NULL AS NUMERIC) AS TOTAL_SINISTRO_2022,
CAST(NULL AS INTEGER) AS SINISTRADOS_2018,
CAST(NULL AS INTEGER) AS SINISTRADOS_2019,
CAST(NULL AS INTEGER) AS SINISTRADOS_2020,
CAST(NULL AS INTEGER) AS SINISTRADOS_2021,
CAST(NULL AS INTEGER) AS SINISTRADOS_2022,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_QUANTIDADE_19_18,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_QUANTIDADE_20_19,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_QUANTIDADE_21_20,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_QUANTIDADE_22_21,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_QUANTIDADE_22_19,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_DIAS_INTERNADO_19_18,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_DIAS_INTERNADO_20_19,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_DIAS_INTERNADO_21_20,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_DIAS_INTERNADO_22_21,
CAST(NULL AS INTEGER) AS VAR_ABS_TOTAL_DIAS_INTERNADO_22_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HM_19_18,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HM_20_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HM_21_20,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HM_22_21,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HM_22_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_19_18,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_20_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_21_20,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_22_21,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_HOSPITALAR_22_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_19_18,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_20_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_21_20,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_22_21,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MATERIAL_22_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_19_18,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_20_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_21_20,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_22_21,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_22_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_SINISTRO_19_18,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_SINISTRO_20_19,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_SINISTRO_21_20,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_SINISTRO_22_21,
CAST(NULL AS NUMERIC) AS VAR_ABS_TOTAL_SINISTRO_22_19,
CAST(NULL AS INTEGER) AS VAR_ABS_SINISTRADOS_19_18,
CAST(NULL AS INTEGER) AS VAR_ABS_SINISTRADOS_20_19,
CAST(NULL AS INTEGER) AS VAR_ABS_SINISTRADOS_21_20,
CAST(NULL AS INTEGER) AS VAR_ABS_SINISTRADOS_22_21,
CAST(NULL AS INTEGER) AS VAR_ABS_SINISTRADOS_22_19

FROM ANOMESCARTPLANO

UNION ALL

SELECT 
DSC_FAIXA_ETARIA,
SIG_UF_PRESTADOR,
ANO,
MES,
ANO_MES,
BASE,
DSC_CARTEIRA,
NME_PLANO_AJUSTADO,
FLG_ORIGEM_PS,
FLG_COVID,
 FLG_DIARIA_UTI_GERAL
  ,FLG_DIARIA_PARTO_UTI_NEONATAL
  ,FLG_DIARIA_PARTO_UTI_ADULTO
  ,FLG_DIARIA_PARTO_UTI_GERAL,
TOTAL_QUANTIDADE_2018,
TOTAL_QUANTIDADE_2019,
TOTAL_QUANTIDADE_2020,
TOTAL_QUANTIDADE_2021,
TOTAL_QUANTIDADE_2022,
TOTAL_DIAS_INTERNADO_2018,
TOTAL_DIAS_INTERNADO_2019,
TOTAL_DIAS_INTERNADO_2020,
TOTAL_DIAS_INTERNADO_2021,
TOTAL_DIAS_INTERNADO_2022,
TOTAL_CUSTO_HM_2018,
TOTAL_CUSTO_HM_2019,
TOTAL_CUSTO_HM_2020,
TOTAL_CUSTO_HM_2021,
TOTAL_CUSTO_HM_2022,
TOTAL_CUSTO_HOSPITALAR_2018,
TOTAL_CUSTO_HOSPITALAR_2019,
TOTAL_CUSTO_HOSPITALAR_2020,
TOTAL_CUSTO_HOSPITALAR_2021,
TOTAL_CUSTO_HOSPITALAR_2022,
TOTAL_CUSTO_MATERIAL_2018,
TOTAL_CUSTO_MATERIAL_2019,
TOTAL_CUSTO_MATERIAL_2020,
TOTAL_CUSTO_MATERIAL_2021,
TOTAL_CUSTO_MATERIAL_2022,
TOTAL_CUSTO_MEDICAMENTOS_2018,
TOTAL_CUSTO_MEDICAMENTOS_2019,
TOTAL_CUSTO_MEDICAMENTOS_2020,
TOTAL_CUSTO_MEDICAMENTOS_2021,
TOTAL_CUSTO_MEDICAMENTOS_2022,
TOTAL_SINISTRO_2018,
TOTAL_SINISTRO_2019,
TOTAL_SINISTRO_2020,
TOTAL_SINISTRO_2021,
TOTAL_SINISTRO_2022,
SINISTRADOS_2018,
SINISTRADOS_2019,
SINISTRADOS_2020,
SINISTRADOS_2021,
SINISTRADOS_2022,
VAR_ABS_TOTAL_QUANTIDADE_19_18,
VAR_ABS_TOTAL_QUANTIDADE_20_19,
VAR_ABS_TOTAL_QUANTIDADE_21_20,
VAR_ABS_TOTAL_QUANTIDADE_22_21,
VAR_ABS_TOTAL_QUANTIDADE_22_19,
VAR_ABS_TOTAL_DIAS_INTERNADO_19_18,
VAR_ABS_TOTAL_DIAS_INTERNADO_20_19,
VAR_ABS_TOTAL_DIAS_INTERNADO_21_20,
VAR_ABS_TOTAL_DIAS_INTERNADO_22_21,
VAR_ABS_TOTAL_DIAS_INTERNADO_22_19,
VAR_ABS_TOTAL_CUSTO_HM_19_18,
VAR_ABS_TOTAL_CUSTO_HM_20_19,
VAR_ABS_TOTAL_CUSTO_HM_21_20,
VAR_ABS_TOTAL_CUSTO_HM_22_21,
VAR_ABS_TOTAL_CUSTO_HM_22_19,
VAR_ABS_TOTAL_CUSTO_HOSPITALAR_19_18,
VAR_ABS_TOTAL_CUSTO_HOSPITALAR_20_19,
VAR_ABS_TOTAL_CUSTO_HOSPITALAR_21_20,
VAR_ABS_TOTAL_CUSTO_HOSPITALAR_22_21,
VAR_ABS_TOTAL_CUSTO_HOSPITALAR_22_19,
VAR_ABS_TOTAL_CUSTO_MATERIAL_19_18,
VAR_ABS_TOTAL_CUSTO_MATERIAL_20_19,
VAR_ABS_TOTAL_CUSTO_MATERIAL_21_20,
VAR_ABS_TOTAL_CUSTO_MATERIAL_22_21,
VAR_ABS_TOTAL_CUSTO_MATERIAL_22_19,
VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_19_18,
VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_20_19,
VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_21_20,
VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_22_21,
VAR_ABS_TOTAL_CUSTO_MEDICAMENTOS_22_19,
VAR_ABS_TOTAL_SINISTRO_19_18,
VAR_ABS_TOTAL_SINISTRO_20_19,
VAR_ABS_TOTAL_SINISTRO_21_20,
VAR_ABS_TOTAL_SINISTRO_22_21,
VAR_ABS_TOTAL_SINISTRO_22_19,
VAR_ABS_SINISTRADOS_19_18,
VAR_ABS_SINISTRADOS_20_19,
VAR_ABS_SINISTRADOS_21_20,
VAR_ABS_SINISTRADOS_22_21,
VAR_ABS_SINISTRADOS_22_19
FROM self-service-saude.SANDBOX_GERAC.LT_GT_SINISTRO_BASE_TOTAL_INTERNACOES_ANALISE_DOR_DATASTUDIO_TESTE
