-- SCRIPT IMPLANTAÇÃO DE PROJETOS

-- Exclusão das tabelas e respectivos relacionamentos
/*
DROP TABLE T_SIP_DEPARTAMENTO CASCADE CONSTRAINTS ;
DROP TABLE T_SIP_DEPENDENTE CASCADE CONSTRAINTS ;
DROP TABLE T_SIP_FUNCIONARIO CASCADE CONSTRAINTS ;
DROP TABLE T_SIP_IMPLANTACAO CASCADE CONSTRAINTS ;
DROP TABLE T_SIP_PROJETO CASCADE CONSTRAINTS ;
*/

-- Criação das tabelas

-- Tabela DEPARTAMENTO
CREATE TABLE T_SIP_DEPARTAMENTO
  (
    cd_depto NUMBER (2) NOT NULL ,
    nm_depto VARCHAR2 (30) NOT NULL
  ) ;

ALTER TABLE T_SIP_DEPARTAMENTO ADD CONSTRAINT PK_SIP_DEPARTAMENTO PRIMARY KEY ( cd_depto ) ;

ALTER TABLE T_SIP_DEPARTAMENTO ADD CONSTRAINT UN_SIP_DEPTO_NOME UNIQUE ( nm_depto ) ;

-- Tabela DEPENDENTE
CREATE TABLE T_SIP_DEPENDENTE
  (
    cd_dependente NUMBER (3) NOT NULL ,
    nr_matricula  NUMBER (5) NOT NULL ,
    nm_dependente VARCHAR2 (60) NOT NULL ,
    dt_nascimento DATE NOT NULL
  ) ;
ALTER TABLE T_SIP_DEPENDENTE ADD CONSTRAINT PK_SIP_DEPENDENTE PRIMARY KEY ( cd_dependente, nr_matricula ) ;


-- Tabela FUNCIONARIO
CREATE TABLE T_SIP_FUNCIONARIO
  (
    nr_matricula   NUMBER (5) NOT NULL ,
    cd_depto       NUMBER (2) NOT NULL ,
    nm_funcionario VARCHAR2 (60) NOT NULL ,
    dt_nascimento  DATE ,
    dt_admissao    DATE NOT NULL ,
    ds_endereco    VARCHAR2 (80) NOT NULL ,
    vl_salario     NUMBER (7,2) NOT NULL
  ) ;

ALTER TABLE T_SIP_FUNCIONARIO ADD CONSTRAINT CK_SPI_FUNC_SALARIO CHECK (VL_SALARIO >= 678) ;

ALTER TABLE T_SIP_FUNCIONARIO ADD CONSTRAINT PK_SIP_FUNCIONARIO PRIMARY KEY ( nr_matricula ) ;

-- Tabela IMPLANTACAO

CREATE TABLE T_SIP_IMPLANTACAO
  (
    cd_implantacao NUMBER (6) NOT NULL ,
    cd_projeto     NUMBER (4) NOT NULL ,
    nr_matricula   NUMBER (5) NOT NULL ,
    dt_entrada     DATE NOT NULL ,
    dt_saida       DATE
  ) ;

ALTER TABLE T_SIP_IMPLANTACAO ADD CONSTRAINT CK_SPI_IMPLAT_DATE CHECK (DT_SAIDA > DT_ENTRADA) ;

ALTER TABLE T_SIP_IMPLANTACAO ADD CONSTRAINT PK_SIP_IMPLANTACAO PRIMARY KEY ( cd_implantacao, cd_projeto ) ;

-- Tabela PROJETO

CREATE TABLE T_SIP_PROJETO
  (
    cd_projeto NUMBER (4) NOT NULL ,
    nm_projeto VARCHAR2 (40) NOT NULL ,
    dt_inicio  DATE NOT NULL ,
    dt_termino DATE
  ) ;

ALTER TABLE T_SIP_PROJETO ADD CONSTRAINT CK_SPI_PROJETO_DATE CHECK (DT_TERMINO > DT_INICIO) ;

ALTER TABLE T_SIP_PROJETO ADD CONSTRAINT PK_SIP_PROJETO PRIMARY KEY ( cd_projeto ) ;

ALTER TABLE T_SIP_PROJETO ADD CONSTRAINT UN_SPI_PROJETO_NOME UNIQUE ( nm_projeto ) ;


-- CHAVES ESTRANGEIRAS

-- Relacionamento entre FUNCIONARIO e DEPARTAMENTO
ALTER TABLE T_SIP_FUNCIONARIO 
	ADD CONSTRAINT FK_DEPTO_FUNC FOREIGN KEY ( cd_depto ) REFERENCES T_SIP_DEPARTAMENTO ( cd_depto ) ;

-- Relacionamento entre DEPENDENTE e FUNCIONARIO
ALTER TABLE T_SIP_DEPENDENTE 
	ADD CONSTRAINT FK_FUNC_DEPENDENTE FOREIGN KEY ( nr_matricula ) REFERENCES T_SIP_FUNCIONARIO ( nr_matricula ) ;

-- Relacionamento entre INPLANTACAO e FUNCIONARIO
ALTER TABLE T_SIP_IMPLANTACAO 
	ADD CONSTRAINT FK_IMPLANTACAO_FUNC FOREIGN KEY ( nr_matricula ) REFERENCES T_SIP_FUNCIONARIO ( nr_matricula ) ;

-- Relacionamento entre IMPLANTACAO e PROJETO
ALTER TABLE T_SIP_IMPLANTACAO 
	ADD CONSTRAINT FK_IMPLANTACAO_PROJETO FOREIGN KEY ( cd_projeto ) REFERENCES T_SIP_PROJETO ( cd_projeto ) ;

